import { chromium, expect } from "@playwright/test";
import { startServer } from "./helpers.js";

// The studio's address. The server hands out the studio page at its deep paths, and every page, selection
// and dialog survives a reload, a direct address and the browser's back and forward buttons.
const password = "test-only-password";
const server = await startServer(4351, password);
const browser = await chromium.launch({ channel: "msedge", headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce" });
context.setDefaultTimeout(20000);
const page = await context.newPage();
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
const pass = (message) => console.log(`PASS ${message}`);
// An absolute address with its query written the way the studio writes it.
const at = (path, query) => server.url + path + (query ? `?${new URLSearchParams(query)}` : "");
const entries = () => page.evaluate(() => history.length);
try {
  for (const path of ["/admin/home", "/admin/models", "/admin/settings/", "/admin/books/alice", "/admin/books/alice/"]) {
    const response = await fetch(server.url + path);
    expect(response.status, path).toBe(200);
    expect(await response.text(), path).toContain('<div id="app"></div>');
  }
  for (const path of ["/admin/zzz", "/admin/books/", "/admin/books/alice/edit"])
    expect((await fetch(server.url + path)).status, path).toBe(404);
  pass("Deep studio paths serve the studio page and unknown ones stay 404");

  await page.goto(at("/admin/books/alice", { chapter: "alice-2" }));
  await page.getByLabel("관리자 비밀번호").fill(password);
  await page.getByRole("button", { name: /스튜디오 들어가기/ }).click();
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  await expect(page.locator('[data-chapter-row="alice-2"]')).toHaveClass(/active/);
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-2" }));
  pass("A deep address waits through the login screen");

  await page.locator("#back-library").click();
  await expect(page.locator(".book-shelf")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/"));
  for (const [name, path, ready] of [["home", "/admin/home", ".home-slides"], ["models", "/admin/models", ".model-grid"], ["settings", "/admin/settings", "#export"]]) {
    await page.locator(`[data-tab="${name}"]`).click();
    await expect(page).toHaveURL(at(path));
    await page.reload();
    await expect(page.locator(ready)).toBeVisible();
    await expect(page.locator(`[data-tab="${name}"]`)).toHaveClass(/active/);
  }
  const tabEntries = await entries();
  await page.locator('[data-tab="settings"]').click();
  expect(await entries()).toBe(tabEntries);
  await page.goBack();
  await expect(page.locator(".model-grid")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/models"));
  await page.goBack();
  await expect(page.locator(".home-slides")).toBeVisible();
  await page.goForward();
  await expect(page.locator(".model-grid")).toBeVisible();
  await page.goto(at("/admin/settings/"));
  await expect(page.locator("#export")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/settings"));
  pass("Each tab has its own path, stays put on reload and follows back and forward");

  await page.locator('[data-tab="books"]').click();
  await page.locator("#book-search").fill("앨리스");
  await expect(page).toHaveURL(at("/admin/", { q: "앨리스" }));
  await page.locator("#book-filter").selectOption("public");
  await expect(page).toHaveURL(at("/admin/", { q: "앨리스", status: "public" }));
  await page.reload();
  await expect(page.locator("#book-search")).toHaveValue("앨리스");
  await expect(page.locator("#book-filter")).toHaveValue("public");
  await expect(page.locator(".book-tile-row:not([hidden])")).toHaveCount(1);
  await page.locator('[data-tab="models"]').click();
  await page.locator("#model-search").fill("토끼");
  await expect(page).toHaveURL(at("/admin/models", { q: "토끼" }));
  await page.reload();
  await expect(page.locator("#model-search")).toHaveValue("토끼");
  await expect(page.locator(".model-card")).toHaveCount(2);
  await page.goBack();
  await expect(page.locator("#book-search")).toHaveValue("앨리스");
  await expect(page.locator(".book-tile-row:not([hidden])")).toHaveCount(1);
  await page.locator("#book-search").fill("");
  await page.locator("#book-filter").selectOption("all");
  await expect(page).toHaveURL(at("/admin/"));
  pass("The shelf search and state filter and the model search live in the query");

  await page.locator('[data-open-book="alice"]').click();
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  const editorEntries = await entries();
  await page.locator('[data-chapter="alice-2"]').click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-2" }));
  const object = await page.locator("#chapter-model-list [data-select-model]").first().getAttribute("data-select-model");
  await page.locator(`#chapter-model-list [data-select-model="${object}"]`).click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-2", object }));
  await page.locator("#asset-search").fill("토끼");
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-2", object, q: "토끼" }));
  expect(await entries()).toBe(editorEntries);
  await page.reload();
  await expect(page.locator('[data-chapter-row="alice-2"]')).toHaveClass(/active/);
  await expect(page.locator(`#chapter-model-list [data-select-model="${object}"]`)).toHaveClass(/active/);
  await expect(page.locator("#object-form")).toBeVisible();
  await expect(page.locator("#asset-search")).toHaveValue("토끼");
  await expect(page.locator(".asset-tile:not([hidden])")).toHaveCount(2);
  await page.goto(at("/admin/books/oz", { chapter: "oz-2" }));
  await expect(page.locator('[data-chapter-row="oz-2"]')).toHaveClass(/active/);
  await expect(page.locator("#asset-search")).toHaveValue("");
  await page.goBack();
  await expect(page.locator(`#chapter-model-list [data-select-model="${object}"]`)).toHaveClass(/active/);
  await page.locator("#back-library").click();
  await expect(page).toHaveURL(at("/admin/"));
  pass("The editor keeps its book, chapter, selection and model search in the address");

  await page.goto(at("/admin/books/nope", { chapter: "x", modal: "book" }));
  await expect(page.locator(".book-shelf")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/"));
  await expect(page.locator("#toast")).toHaveText("요청한 도서를 찾을 수 없어 도서 보관함을 열었어요.");
  await page.goto(at("/admin/books/alice", { chapter: "nope" }));
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  await expect(page.locator("#toast")).toHaveText("요청한 챕터를 찾을 수 없어 첫 챕터를 열었어요.");
  await page.goto(at("/admin/books/alice", { chapter: "alice-1", object: "nope" }));
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  await expect(page.locator("#toast")).toHaveText("요청한 오브젝트를 찾을 수 없어 선택하지 않았어요.");
  await page.goto(at("/admin/books/alice", { chapter: "alice-1", object: "decor-0" }));
  await expect(page.locator("#delete-floor-object")).toBeVisible();
  await page.goto(at("/admin/", { status: "xyz", modal: "bogus", foo: "1" }));
  await expect(page.locator(".book-shelf")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/"));
  pass("Unknown books, chapters and objects fall back with a notice and stray parameters drop out");

  await page.locator('[data-open-book="alice"]').click();
  await page.locator("#chapter-model-list [data-select-model]").first().click();
  await page.locator('#object-form [name="title"]').fill("저장하지 않은 이름");
  await page.locator('#object-form [name="title"]').press("Tab");
  const editorUrl = page.url();
  await page.goBack();
  await expect(page.locator(".leave-editor-dialog")).toBeVisible();
  await expect(page).toHaveURL(editorUrl);
  await page.getByRole("button", { name: "계속 편집", exact: true }).click();
  await expect(page.locator(".leave-editor-dialog")).toHaveCount(0);
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  await page.goBack();
  await page.getByRole("button", { name: "저장하지 않고 나가기", exact: true }).click();
  await expect(page.locator(".book-shelf")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/"));
  pass("Back out of an editor with unsaved changes asks first and keeps the editor's address while asking");

  await page.locator('[data-open-book="alice"]').click();
  await page.evaluate(() => { window.__canvas = document.querySelector("#studio-world canvas"); });
  await page.locator("#edit-book").click();
  await expect(page.locator("#book-form")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", modal: "book" }));
  await page.goBack();
  await expect(page.locator("#book-form")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  expect(await page.evaluate(() => document.querySelector("#studio-world canvas") === window.__canvas)).toBe(true);
  await page.goForward();
  await expect(page.locator("#book-form")).toBeVisible();
  await page.reload();
  await expect(page.locator("#book-form")).toBeVisible();
  await page.getByRole("button", { name: "닫기", exact: true }).click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  await page.goBack();
  await expect(page.locator(".book-shelf")).toBeVisible();
  pass("A dialog gets its own entry: back closes it without rebuilding the editor, and a reloaded one steps back on close");

  await page.locator('[data-open-book="alice"]').click();
  await page.locator('[data-chapter="alice-2"]').click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-2" }));
  await page.locator("#edit-book").click();
  await page.locator('#book-form button[type="submit"]').click();
  await expect(page.locator("#book-form")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", object: "a1-rabbit" }));
  await page.locator("#undo").click();
  await page.locator("#back-library").click();
  await expect(page.locator(".book-shelf")).toBeVisible();
  pass("Applying a dialog leaves the page's new place in the address");

  await page.locator('[data-open-book="alice"]').click();
  await page.locator('[data-chapter-edit="alice-2"]').click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", modal: "chapter", id: "alice-2" }));
  await page.reload();
  await expect(page.locator("dialog .eyebrow")).toHaveText("CHAPTER 2");
  await page.getByRole("button", { name: "닫기", exact: true }).click();
  await page.locator("#edit-book").click();
  await expect(page.locator("#book-form")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", modal: "book" }));
  await page.goBack();
  await expect(page.locator("#book-form")).toHaveCount(0);
  await expect(page.locator("#chapter-form")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  await page.locator('[data-model-edit="rabbit"]').click();
  await expect(page.locator("#model-form")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", modal: "model", id: "rabbit" }));
  await page.keyboard.press("Escape");
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  await page.locator("#new-model").click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", modal: "new-model" }));
  await page.goBack();
  await expect(page.locator("#model-form")).toHaveCount(0);
  await page.locator("#back-library").click();
  await page.locator('[data-tab="models"]').click();
  await page.locator('[data-preview-model="rabbit"]').click();
  await expect(page.locator("#single-preview")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/models", { modal: "model-preview", id: "rabbit" }));
  await page.reload();
  await expect(page.locator("#single-preview")).toBeVisible();
  await page.goBack();
  await expect(page.locator("#single-preview")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/models"));
  await page.goto(at("/admin/models", { modal: "model", id: "rabbit" }));
  await expect(page.locator("#model-form")).toBeVisible();
  await page.getByRole("button", { name: "닫기", exact: true }).click();
  await expect(page).toHaveURL(at("/admin/models"));
  await page.goto(at("/admin/models", { modal: "model", id: "nope" }));
  await expect(page.locator("#toast")).toHaveText("요청한 항목을 찾을 수 없어 창을 열지 않았어요.");
  await expect(page).toHaveURL(at("/admin/models"));
  pass("Chapter, model and model preview dialogs keep their address, even when one opens right after another closes");

  const fresh = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce" });
  const guest = await fresh.newPage();
  guest.on("pageerror", (error) => errors.push(error.message));
  await guest.goto(at("/admin/models", { modal: "model", id: "rabbit" }));
  await guest.getByLabel("관리자 비밀번호").fill(password);
  await guest.getByRole("button", { name: /스튜디오 들어가기/ }).click();
  await expect(guest.locator("#model-form")).toBeVisible();
  await expect(guest).toHaveURL(at("/admin/models", { modal: "model", id: "rabbit" }));
  await fresh.close();
  pass("A dialog's address also waits through the login screen");

  await page.locator('[data-tab="books"]').click();
  await page.locator("#new-book").click();
  await expect(page).toHaveURL(at("/admin/", { modal: "new-book" }));
  await page.locator('#book-form [name="title"]').fill("주소 검사 책");
  await page.locator('#book-form button[type="submit"]').click();
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  await expect(page).toHaveURL(/\/admin\/books\/[0-9a-f-]{36}\?chapter=[0-9a-f-]{36}$/);
  await page.goBack();
  await page.getByRole("button", { name: "저장하지 않고 나가기", exact: true }).click();
  await expect(page.locator(".book-shelf")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/"));
  pass("A new book's editor takes over the dialog's entry, so back returns to the shelf");

  const puts = [];
  page.on("request", (request) => { if (request.method() === "PUT" && request.url().endsWith("/api/studio")) puts.push(request.url()); });
  const frameHistory = () => page.evaluate(() => document.querySelector(".client-preview-dialog iframe")?.contentWindow?.history.pushState.name);
  const preview = () => page.frames().find((frame) => frame.url().includes("preview=draft"));
  await page.locator('[data-tab="home"]').click();
  await page.locator("#preview-home").click();
  await expect(page.locator(".client-preview-dialog iframe")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/home", { modal: "home-preview" }));
  expect(puts.length).toBe(1);
  await page.reload();
  await expect(page.locator(".client-preview-dialog iframe")).toBeVisible();
  expect(puts.length).toBe(1);
  await expect.poll(frameHistory).toBe("bound replaceState");
  await preview().evaluate(() => history.pushState(null, "", `${location.pathname}${location.search}&probe=1`));
  await page.goBack();
  await expect(page.locator(".client-preview-dialog")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/home"));
  await page.locator("#preview-home").click();
  await expect.poll(frameHistory).toBe("bound replaceState");
  await preview().evaluate(() => { setTimeout(() => location.assign(`${location.pathname}${location.search}&probe=2`)); });
  await expect.poll(() => preview()?.url() ?? "").toContain("probe=2");
  await expect.poll(frameHistory).toBe("bound replaceState");
  await page.locator(".client-preview-dialog .close-modal").click();
  await expect(page).toHaveURL(at("/admin/home"));
  await page.locator('[data-tab="models"]').click();
  await expect(page).toHaveURL(at("/admin/models"));
  pass("The home preview reopens without saving, its frame keeps no history, and closing it never stalls later moves");

  await page.locator('[data-tab="books"]').click();
  await page.locator('[data-open-book="alice"]').click();
  const readerEntries = await entries();
  await page.locator("#preview-client").click();
  await expect(page.locator(".inplace-reader")).toBeVisible();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", mode: "reader" }));
  await page.locator(".reader-mode-bar select").selectOption("2");
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-3", mode: "reader" }));
  expect(await entries()).toBe(readerEntries);
  await page.locator("#exit-reader").click();
  await expect(page.locator(".inplace-reader")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1" }));
  await page.locator("#preview-client").click();
  await page.locator(".reader-mode-bar select").selectOption("2");
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-3", mode: "reader" }));
  await page.reload();
  await expect(page.locator(".inplace-reader")).toBeVisible();
  await expect(page.locator(".reader-mode-bar select")).toHaveValue("2");
  await page.locator("#exit-reader").click();
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-3" }));
  await expect(page.locator('[data-chapter-row="alice-3"]')).toHaveClass(/active/);
  await page.goto(at("/admin/books/alice", { chapter: "alice-1", mode: "reader", modal: "book" }));
  await expect(page.locator(".inplace-reader")).toBeVisible();
  await expect(page.locator("#book-form")).toHaveCount(0);
  await expect(page).toHaveURL(at("/admin/books/alice", { chapter: "alice-1", mode: "reader" }));
  pass("Reader mode and its chapter live in the address and come back after a reload");

  const tilesOpen = () => page.locator(".world-tiles details").evaluate((details) => details.open);
  await page.locator("#exit-reader").click();
  await page.locator(".world-tiles summary").click();
  await expect.poll(tilesOpen).toBe(false);
  await page.reload();
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  expect(await tilesOpen()).toBe(false);
  expect(await page.locator(".world-assets details").evaluate((details) => details.open)).toBe(true);
  await page.locator("[data-chapter-drag]").first().press("Alt+ArrowDown");
  await expect(page.locator("[data-chapter-row]").first()).toHaveAttribute("data-chapter-row", "alice-2");
  expect(await tilesOpen()).toBe(false);
  await page.locator("#undo").click();
  await expect(page.locator("[data-chapter-row]").first()).toHaveAttribute("data-chapter-row", "alice-1");
  await page.locator("#back-library").click();
  await page.locator('[data-open-book="oz"]').click();
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  expect(await tilesOpen()).toBe(false);
  await page.locator(".world-tiles summary").click();
  await expect.poll(tilesOpen).toBe(true);
  await page.locator("#back-library").click();
  pass("Editor panels stay folded through reloads, redraws and other books");

  await page.route("**/api/studio", async (route) => {
    if (route.request().method() !== "GET") return route.continue();
    const response = await route.fetch();
    const body = await response.json();
    const alice = body.library.books[0];
    body.library.books = Array.from({ length: 18 }, (_, i) => ({ ...structuredClone(alice), id: `shelf-${i}`, title: `${alice.title} ${i + 1}` }));
    body.library.home = { hero: [] };
    await route.fulfill({ response, json: body });
  });
  // The Korean web font (shared/style.css) is fetched from Google Fonts and swaps in a little after first
  // paint, growing the tile text a few pixels; blocked here so the tile layout (and the scroll target
  // computed from it) stays put instead of racing the studio's own scroll save and restore.
  await page.route(/fonts\.(googleapis|gstatic)\.com/, (route) => route.abort());
  await page.goto(at("/admin/"));
  await expect(page.locator(".book-tile")).toHaveCount(18);
  const middle = await page.evaluate(() => { const top = Math.floor((document.documentElement.scrollHeight - innerHeight) / 2); scrollTo(0, top); return top; });
  expect(middle).toBeGreaterThan(300);
  await expect.poll(() => page.evaluate(() => history.state?.scroll)).toBe(middle);
  await page.reload();
  await expect(page.locator(".book-tile")).toHaveCount(18);
  expect(await page.evaluate(() => scrollY)).toBe(middle);
  await page.evaluate(() => document.querySelector('[data-open-book="shelf-5"]').click());
  await expect(page.locator("#studio-world canvas")).toBeVisible();
  await page.goBack();
  await expect(page.locator(".book-tile")).toHaveCount(18);
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(middle);
  await page.evaluate(() => document.querySelector('[data-open-book="shelf-5"]').click());
  await page.locator("#back-library").click();
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(middle);
  await page.locator('[data-tab="home"]').click();
  expect(await page.evaluate(() => scrollY)).toBe(0);
  await page.unroute("**/api/studio");
  await page.unroute(/fonts\.(googleapis|gstatic)\.com/);
  pass("The shelf returns to its scroll after a reload, back and the 도서 보관함 button, and a new page starts at the top");

  expect(errors).toEqual([]);
} finally {
  await browser.close();
  await server.stop();
}
