import {chromium,expect} from '@playwright/test';
import {startServer,sampleGLB} from './helpers.js';
const server=await startServer(4294);const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1600,height:1000}});context.setDefaultTimeout(20000);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('**/assets/admin-*.js',async route=>{const response=await route.fetch();const body=(await response.text()).replace(/return\{world:(\w+),dispose\(\)/,'return window.__editorWorld=$1,{world:$1,dispose()').replace(/(\w+)\.setActive\(!0\)/,'$1.setActive(!0),(window.__testReader=$1)');await route.fulfill({response,body});});
try{
 await page.goto(server.url+'/admin/');await expect(page.locator('.book-tile')).toHaveCount(2);await page.screenshot({path:'docs/floor-evidence/new-library.png'});
 await page.locator('[data-open-book="alice"]').click();
 const originalChapters=await page.locator('[data-chapter-row]').evaluateAll(rows=>rows.map(r=>r.dataset.chapterRow));
 await page.evaluate(()=>{window.__originalCanvas=document.querySelector('#studio-world canvas');window.__originalCamera=window.__editorWorld.camera;});
 await page.locator('[data-chapter]').nth(1).click();
 await page.waitForFunction(()=>document.querySelector('.world-workspace').dataset.travelling==='false');
 expect(await page.evaluate(()=>document.querySelector('#studio-world canvas')===window.__originalCanvas&&window.__editorWorld.camera===window.__originalCamera)).toBe(true);
 expect(await page.evaluate(()=>window.__editorWorld.controls.target.x)).toBeCloseTo(await page.evaluate(()=>64+window.__editorWorld.chapter.placements.find(p=>p.id===window.__editorWorld.chapter.mainPlacementId).x));
 await page.locator('[data-select-model]').first().click();const localX=await page.evaluate(()=>window.__editorWorld.chapter.placements[0].x);await expect(page.locator('#object-form [name="x"]')).toHaveValue(String(localX));
 await page.locator('[data-chapter]').nth(2).click();await page.locator('[data-chapter]').first().click();await page.waitForFunction(()=>document.querySelector('.world-workspace').dataset.travelling==='false');
 expect(await page.evaluate(()=>window.__editorWorld.controls.target.x)).toBeCloseTo(await page.evaluate(()=>window.__editorWorld.chapter.placements.find(p=>p.id===window.__editorWorld.chapter.mainPlacementId).x));
 await expect(page.locator('#edit-story')).toHaveCount(0);await expect(page.locator('.world-chapters summary #add-chapter')).toHaveCount(0);
 await page.locator('[data-chapter-edit]').nth(1).click();
 const secondTitle=await page.evaluate(()=>window.__editorWorld.chapter.title);
 await expect(page.locator('#chapter-form [name="title"]')).not.toHaveValue(secondTitle);await page.getByRole('button',{name:'닫기',exact:true}).click();
 await page.locator('[data-chapter-drag]').first().dragTo(page.locator('[data-chapter-row]').nth(1),{targetPosition:{x:100,y:40}});
 await expect(page.locator('[data-chapter-row]').nth(1)).toHaveAttribute('data-chapter-row',originalChapters[0]);
 expect(await page.evaluate(()=>window.__editorWorld.chapter.id)).toBe(originalChapters[0]);
 await page.locator('#save').click();await expect(page.locator('#save-state')).toHaveText('변경사항 저장됨');
 const reordered=await(await context.request.get(server.url+'/api/studio')).json();expect(reordered.library.books.find(b=>b.id==='alice').chapters[1].id).toBe(originalChapters[0]);
 await page.locator('#undo').click();await expect(page.locator('[data-chapter-row]').first()).toHaveAttribute('data-chapter-row',originalChapters[0]);
 for(const axis of ['X','Y','Z','−X','−Y','−Z']){await page.getByRole('button',{name:axis+'축에서 보기',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.view-orientation').dataset.animating==='false');const vector=await page.evaluate(()=>window.__editorWorld.camera.position.clone().sub(window.__editorWorld.controls.target).normalize().toArray());const index={'X':0,'Y':1,'Z':2}[axis.at(-1)];expect(vector[index]).toBeCloseTo(axis.startsWith('−')?-1:1,3);}
 const pose=await page.evaluate(()=>window.__editorWorld.camera.position.toArray());
 await page.locator('#preview-client').click();await expect(page.locator('dialog')).toHaveCount(0);await expect(page.locator('.inplace-reader canvas')).toBeVisible();
 await page.waitForFunction(()=>window.__testReader?.player.position.y>.1);await page.waitForFunction(()=>window.__testReader?.arrivalTime===null);
 await page.waitForFunction(()=>window.__testReader.readingActive?.p.id===window.__testReader.zones[0].chapter.mainPlacementId);
 await page.evaluate(()=>{const r=window.__testReader,o=r.objects.filter(o=>o.chapterIndex===0).at(-1);window.__supportId=o.p.id;r.player.position.set(o.p.x,0,o.p.z+1.8);r.target.copy(r.player.position);});
 await page.waitForFunction(()=>window.__testReader.objects.find(o=>o.p.id===window.__supportId).near&&window.__testReader.readingActive===null);
 await expect(page.locator('.inplace-reader .floor-reading-controls')).toBeHidden();
 const start=await page.evaluate(()=>window.__testReader.player.position.x);await page.keyboard.down('ArrowRight');await page.waitForTimeout(300);await page.keyboard.up('ArrowRight');expect(await page.evaluate(()=>window.__testReader.player.position.x)).toBeGreaterThan(start);
 await page.locator('#exit-reader').click();await expect(page.locator('.inplace-reader')).toHaveCount(0);expect(await page.evaluate(()=>window.__editorWorld.camera.position.toArray())).toEqual(pose);
 await page.locator('#back-library').click();
 await page.locator('#new-book').click();await page.getByLabel('책 제목',{exact:true}).fill('격자 월드 테스트');await page.getByRole('button',{name:'책 만들기',exact:true}).click();
 await expect(page.locator('.world-workspace')).toBeVisible();await expect(page.locator('#studio-world canvas')).toBeVisible();await expect(page.locator('.world-empty')).toBeVisible();
 expect(await page.locator('#studio-world').boundingBox()).toMatchObject({x:0,y:0,width:1600,height:1000});
 await expect(page.locator('.world-tools #edit-floor')).toHaveCount(0);
 await page.locator('[data-floor-asset="arrow"]').dragTo(page.locator('#studio-world'),{targetPosition:{x:850,y:550}});
 expect(await page.evaluate(()=>window.__editorWorld.chapter.floorDecals.at(-1).rotation)).toBe(0);
 for(const [name,value] of [['x','12'],['y','2'],['z','8'],['rotation','90'],['width','5']]){await page.locator(`#object-form [name="${name}"]`).fill(value);await page.locator(`#object-form [name="${name}"]`).press('Tab');}
 expect(await page.evaluate(()=>window.__editorWorld.chapter.floorDecals.at(-1))).toMatchObject({x:12,y:2,z:8,rotation:90,width:5});
 await page.keyboard.press('Escape');
 const imagePoint=await page.evaluate(()=>{const w=window.__editorWorld,m=w.floorArt.children.find(m=>m.userData.floorDecalId),p=m.position.clone().project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});
 await page.mouse.click(imagePoint.x,imagePoint.y);await expect(page.locator('#object-form [name="width"]')).toHaveValue('5');
 const basic=page.locator('.asset-tile').filter({hasText:'하얀 토끼'});await basic.locator('img').dragTo(page.locator('#studio-world'),{targetPosition:{x:820,y:480}});
 await expect(page.locator('#object-form [name="animation"]')).toBeVisible();
 await basic.locator('img').dragTo(page.locator('#studio-world'),{targetPosition:{x:820,y:480}});await expect(page.locator('[data-select-model]')).toHaveCount(1);
 await page.locator('#save').click();await expect(page.locator('#save-state')).toHaveText('변경사항 저장됨');
 await page.locator('#delete-object').click();
 await page.locator('#new-model').click();await page.getByLabel('모델 이름',{exact:true}).fill('뼈대 테스트 모델');await page.getByLabel('제작자 및 사용 권한').fill('테스트 직접 제작');
 await page.getByLabel('3D 모델 파일 선택',{exact:true}).setInputFiles({name:'rig.glb',mimeType:'model/gltf-binary',buffer:sampleGLB()});
 await expect(page.locator('#upload-status')).toContainText('업로드 완료');await page.getByRole('button',{name:'보관함에 등록',exact:true}).click();
 const card=page.locator('.asset-tile').filter({hasText:'뼈대 테스트 모델'});await expect(card).toBeVisible();
 await card.locator('img').dragTo(page.locator('#studio-world'),{targetPosition:{x:780,y:470}});
 await expect(page.locator('#object-form')).toBeVisible();await expect(page.locator('[name="clip"]')).toHaveValue('Float');
 await expect(page.locator('.world-minimap')).toHaveCount(0);
 await page.locator('#tool-scale').click();await page.waitForTimeout(150);
 const scaleHandle=await page.evaluate(()=>{const w=window.__editorWorld,root=w.scene.children.find(o=>o.controls?.setMode),gizmo=root.children.find(o=>o.type==='TransformControlsGizmo'),mesh=gizmo.gizmo.scale.children.find(o=>o.name==='XYZ');mesh.updateWorldMatrix(true,false);mesh.geometry.computeBoundingBox();const v=mesh.geometry.boundingBox.getCenter(w.camera.position.clone()).applyMatrix4(mesh.matrixWorld).project(w.camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};});
 await page.mouse.move(scaleHandle.x,scaleHandle.y);await page.mouse.down();await page.mouse.move(scaleHandle.x+70,scaleHandle.y,{steps:12});await page.mouse.up();expect(await page.evaluate(()=>window.__editorWorld.chapter.placements[0].scale)).toBeGreaterThan(1);
 await page.locator('#object-form [name="scale"]').fill('1');await page.locator('#object-form [name="scale"]').press('Tab');
 await page.locator('#tool-radius').click();
 const radiusHandle=await page.evaluate(()=>{const w=window.__editorWorld,h=w.scene.getObjectByName('placement-ranges').children.find(o=>o.userData.radiusHandle),v=h.position.clone().project(w.camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};});
 await page.mouse.move(radiusHandle.x,radiusHandle.y);await page.mouse.down();await page.mouse.move(radiusHandle.x+60,radiusHandle.y,{steps:12});await page.mouse.up();expect(await page.evaluate(()=>window.__editorWorld.chapter.placements[0].radius)).toBeGreaterThan(2);
 await page.locator('#object-form [name="radius"]').fill('4');await page.locator('#object-form [name="radius"]').press('Tab');await page.locator('#tool-move').click();
 await page.locator('#grid-step').selectOption('2');
 await page.waitForFunction(()=>window.__editorWorld?.scene);
 const handle=await page.evaluate(()=>{const w=window.__editorWorld,root=w.scene.children.find(o=>o.controls?.setMode),gizmo=root.children.find(o=>o.type==='TransformControlsGizmo'),mesh=gizmo.gizmo.translate.children.find(o=>o.name==='X');mesh.geometry.computeBoundingBox();const v=mesh.geometry.boundingBox.getCenter(w.camera.position.clone()).applyMatrix4(mesh.matrixWorld).project(w.camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2,original:w.chapter.placements[0].x};});
 await page.mouse.move(handle.x,handle.y);await page.mouse.down();await page.mouse.move(handle.x+100,handle.y,{steps:12});await page.mouse.up();
 const moved=await page.evaluate(()=>window.__editorWorld.chapter.placements[0].x);expect(moved).not.toBe(handle.original);expect(moved%2).toBe(0);
 for(const [name,value] of [['x','4'],['y','6'],['z','-4'],['rotation','90'],['radius','10']]){await page.locator(`#object-form [name="${name}"]`).fill(value);await page.locator(`#object-form [name="${name}"]`).press('Tab');}
 await page.locator('#play-clip').click();await page.screenshot({path:'docs/floor-evidence/new-workspace.png'});
 await page.locator('#duplicate-object').click();await expect(page.locator('[data-select-model]')).toHaveCount(2);await page.locator('#undo').click();await expect(page.locator('[data-select-model]')).toHaveCount(1);await page.locator('#redo').click();await expect(page.locator('[data-select-model]')).toHaveCount(2);
 const copyId=await page.evaluate(()=>window.__editorWorld.chapter.placements[1].id),firstId=await page.evaluate(()=>window.__editorWorld.chapter.placements[0].id);
 await page.locator(`[data-select-model="${copyId}"]`).click();await page.locator('#make-main').click();expect(await page.evaluate(()=>window.__editorWorld.chapter.mainPlacementId)).toBe(copyId);
 await page.locator('#undo').click();expect(await page.evaluate(()=>window.__editorWorld.chapter.mainPlacementId)).toBe(firstId);await page.locator('#redo').click();
 await page.locator(`[data-select-model="${copyId}"]`).click();await page.locator('#delete-object').click();await expect(page.getByRole('heading',{name:'메인 모델 삭제'})).toBeVisible();await page.locator('[name="replacement"]').selectOption(firstId);await page.getByRole('button',{name:'선택하고 삭제'}).click();await expect(page.locator('[data-select-model]')).toHaveCount(1);expect(await page.evaluate(()=>window.__editorWorld.chapter.mainPlacementId)).toBe(firstId);
 await page.locator('#undo').click();await expect(page.locator('[data-select-model]')).toHaveCount(2);expect(await page.evaluate(()=>window.__editorWorld.chapter.mainPlacementId)).toBe(copyId);
 await page.locator(`[data-select-model="${firstId}"]`).click();await page.locator('#make-main').click();
 await page.locator('#save').click();await expect(page.locator('#save-state')).toHaveText('변경사항 저장됨');
 let saved=await(await context.request.get(server.url+'/api/studio')).json();const book=saved.library.books.find(b=>b.title==='격자 월드 테스트'),p=book.chapters[0].placements[0];expect(p).toMatchObject({x:4,y:6,z:-4,rotation:90,radius:5,animation:'clip',clip:'Float'});
 expect(book.chapters[0].mainPlacementId).toBe(firstId);
 expect(book.chapters[0].floorDecals[0]).toMatchObject({x:12,y:2,z:8,rotation:90,width:5});
 await page.locator('[data-chapter-edit]').first().click();await page.getByLabel('오른쪽에 보여 줄 글귀',{exact:true}).fill('새로운 챕터의 내용');await page.getByRole('button',{name:'변경 적용',exact:true}).click();
 await page.locator('#edit-book').click();await page.getByLabel('작가',{exact:true}).fill('테스트 저자');await page.getByLabel('권리 및 번역·각색 정보').fill('직접 작성한 테스트');await page.getByLabel('사용자 화면 공개 대상에 포함').check();await page.getByRole('button',{name:'변경 적용',exact:true}).click();
 await page.locator('#publish').click();await expect(page.locator('#save-state')).toHaveText('공개 완료');const live=await(await context.request.get(server.url+'/api/library')).json();expect(live.books.find(b=>b.id===book.id).chapters[0].placements[0].y).toBe(6);
 await page.reload();await page.getByRole('button',{name:/격자 월드 테스트/}).click();await expect(page.locator('[data-select-model]')).toHaveCount(2);
 await page.locator('.world-chapter-tabs #add-chapter').click();await expect(page.locator('#chapter-form')).toBeVisible();await expect(page.locator('[data-chapter-row]')).toHaveCount(2);await page.getByRole('button',{name:'닫기',exact:true}).click();await page.locator('#undo').click();await expect(page.locator('[data-chapter-row]')).toHaveCount(1);
 const rejected=await context.request.post(server.url+'/api/models/upload',{headers:{'X-On-The-Book':'studio'},multipart:{model:{name:'notrigged.glb',mimeType:'model/gltf-binary',buffer:sampleGLB(false)}}});expect(rejected.status()).toBe(400);
 await page.setViewportSize({width:1000,height:760});await expect(page.locator('#save')).toBeVisible();
 expect(errors).toEqual([]);console.log('PASS book creation, full-screen world, rigged upload, drag/drop, snapped XYZ, clip/radius, undo/redo, persistence and publish; unrigged upload rejected');
}finally{await browser.close();await server.stop();}



