import { floorArt, defaultDecals, layout, terrain } from "../shared/landscape.js";
import { orientationWidget, inlineReader } from "./viewport-tools.js";
import * as THREE from 'three';
import { TransformControls } from 'three/addons/controls/TransformControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { World, makeModel } from '../shared/world.js';
import { esc, uid, toast, api, modal } from '../shared/ui.js';
import { overlapsTrigger, reactionSize, triggerCircles, mainModel } from '../shared/experience.js';
import './workspace.css';

export function shelfHTML(books) {
 return `<section class="book-library"><div class="library-heading"><div><small>ON THE BOOK / STUDIO</small><h1>이야기의 세계를 만드세요.</h1><p>책을 열고, 챕터를 나누고, 장면에 생명을 불어넣으세요.</p></div><button id="new-book" class="primary-button">＋ 새 도서 추가</button></div><div class="library-filter"><input id="book-search" aria-label="도서 검색" placeholder="도서 제목 검색"><select id="book-filter" aria-label="도서 상태"><option value="all">모든 도서</option><option value="draft">비공개 초안</option><option value="public">공개 대상</option></select></div><div class="book-shelf">${books.map((b,i)=>`<button class="book-tile" data-open-book="${b.id}" data-title="${esc(b.title.toLowerCase())}" data-state="${b.published?'public':'draft'}"><div class="book-cover" style="--cover-hue:${135+i*27}">${b.cover?`<img src="${esc(b.cover)}" alt="">`:`<span>ON THE BOOK</span><strong>${esc(b.title)}</strong><i>✧</i><small>${esc(b.author||'새로운 이야기')}</small>`}</div><div class="book-tile-info"><strong>${esc(b.title)}</strong><span>${b.chapters.length}개 챕터 · ${b.published?'공개 대상':'비공개 초안'}</span><em>월드 편집 ↗</em></div></button>`).join('')}</div><p id="shelf-empty" hidden>일치하는 도서가 없습니다. 새 도서를 추가해 시작하세요.</p></section>`;
}
export function mountWorkspace(app, {book,chapter,models,selectedId,hooks}) {
 const zones=layout(book.chapters),zoneFor=id=>zones.find(z=>z.chapter.id===id);
 const worldBounds={start:zones[0].start,end:zones.at(-1).end,depth:Math.max(...zones.map(z=>z.depth))};
 let cameraFrame=0;let rangeLayer=null,radiusDrag=null,scaleGesture=null;const chapterScenes=new Map();
 let selected=selectedId,step=1,mode='translate',dead=false,dragModel=null,readerMode=null;
 const eligible=m=>m&&(m.kind!=='glb'||(m.rigged&&m.clips?.length));
 app.innerHTML=`<div class="world-workspace"><div id="studio-world"></div><header class="world-topbar"><button id="back-library">← 도서 보관함</button><strong>${esc(book.title)}</strong><button id="edit-book">도서 정보</button><span class="toolbar-spacer"></span><span id="save-state"></span><button id="undo" ${hooks.canUndo?'':'disabled'}>↶ 실행 취소</button><button id="redo" ${hooks.canRedo?'':'disabled'}>↷ 다시 실행</button><button id="save">임시 저장</button><button id="publish" class="accent">공개</button></header>
 <aside class="world-assets floating-panel"><details open><summary>모델 보관함 <button id="new-model">＋ 등록</button></summary><p class="placement-target" id="placement-target"></p><input id="asset-search" placeholder="모델 검색" aria-label="모델 검색"><p class="panel-note">모델을 월드로 드래그하세요. 마우스를 올리면 동작을 미리 봅니다.</p><div class="asset-tray">${[...models].sort((a,b)=>Number(!!eligible(b))-Number(!!eligible(a))).map(m=>`<div class="asset-tile" draggable="${!!eligible(m)}" data-model="${m.id}" data-name="${esc(m.name.toLowerCase())}"><div class="asset-preview" data-thumb="${m.id}"></div><strong>${esc(m.name)}</strong><small>${eligible(m)?(m.kind!=="glb"?"기본 동작 · 드래그 배치":`${m.clips.length}개 동작`):'기존 모델 · 새 배치 불가'}</small><button data-model-edit="${m.id}">정보</button></div>`).join('')}</div></details></aside>
 <aside class="world-tiles floating-panel"><details open><summary>바닥 이미지</summary><p class="panel-note">이미지를 끌어 배치하고, 월드에서 선택해 수정하세요.</p><div class="tile-tray"></div><label class="floor-upload">＋ PNG 등록<input id="upload-floor-asset" type="file" accept="image/png" hidden></label></details></aside>
 <div class="world-right-sidebar"> <aside class="world-chapters floating-panel"><details open><summary>챕터</summary><div class="world-chapter-tabs" aria-label="챕터 목록">${book.chapters.map((c,i)=>`<div class="chapter-row ${c.id===chapter.id?'active':''}" data-chapter-row="${c.id}"><button class="chapter-drag" draggable="true" data-chapter-drag="${c.id}" aria-label="${esc(c.title)} 순서 이동" title="드래그하여 순서 변경 · Alt+↑↓"><svg viewBox="0 0 16 20" aria-hidden="true"><path d="M5 4h0m6 0h0M5 10h0m6 0h0M5 16h0m6 0h0"/></svg></button><button class="chapter-open" data-chapter="${c.id}"><span class="chapter-number">${String(i+1).padStart(2,'0')} </span>${esc(c.title)}<small data-count-chapter="${c.id}">${c.placements.length?`모델 ${c.placements.length}개`:'모델 없음'}</small></button><button class="chapter-edit" data-chapter-edit="${c.id}" aria-label="${esc(c.title)} 편집" title="챕터 편집"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m12.5 3.5 4 4M3 17l4.5-1 10-10a2.8 2.8 0 0 0-4-4l-10 10Z"/></svg></button></div>`).join('')}<button id="add-chapter" class="chapter-add"><span aria-hidden="true">＋</span> 챕터 추가</button></div></details></aside> <aside class="world-chapter-models floating-panel"><details open><summary>챕터 모델</summary><div id="chapter-model-list"></div></details></aside> <aside class="world-inspector floating-panel"><details open><summary>선택한 오브젝트</summary><div id="object-properties"></div></details></aside></div>
 <div class="world-tools floating-panel"><button id="tool-move" class="active">이동 W</button><button id="tool-rotate">방향 E</button><button id="tool-scale">크기 S</button><button id="tool-radius">발동 범위 R</button><label>격자 <select id="grid-step"><option value="0.5">0.5</option><option selected value="1">1</option><option value="2">2</option></select></label><button id="scene-reset">시점 초기화</button><button id="preview-client">▶ 독자 체험</button></div>

 <footer class="world-status"><span id="world-hint">왼쪽 드래그: 회전 · 오른쪽 드래그: 화면 이동 · 휠: 확대</span><span>격자 스냅 ON · 회전 15° · 금색: 반응 범위 / 붉은색: 충돌</span></footer></div>`;
 const el=id=>app.querySelector('#'+id);
 const world=new World(el('studio-world'),{chapter,models,editor:true,onError:toast,onSelect:id=>{if(!transform.dragging&&!suppressSelection){const owner=book.chapters.find(c=>c.placements.some(p=>p.id===id));if(owner&&owner.id!==chapter.id)changeChapter(owner.id,false);selectObject(id);}},onMove:()=>{if(!transform.dragging&&!suppressSelection)selectObject(null);}});
 world.onSelectFloor=(id,ownerId)=>{if(!transform.dragging&&!suppressSelection){const owner=book.chapters.find(c=>c.id===ownerId);if(owner&&owner.id!==chapter.id)changeChapter(owner.id,false);if(!chapter.floorDecals)chapter.floorDecals=defaultDecals(chapter);selectObject(id);}};
 let suppressSelection=false;
 const current=()=>chapter.placements.find(p=>p.id===selected)||chapter.floorDecals?.find(p=>p.id===selected);
 function refreshFloor(){world.disposeTree(world.floorArt);world.root.remove(world.floorArt);const circles=triggerCircles(book);let edge=-(book.chapters[0]?.width||64)/2;for(const c of book.chapters){if(c.id===chapter.id){edge+=c.width/2;break;}edge+=c.width;}world.floorArt=floorArt(world.root,chapter,0,circles.map(p=>({...p,x:p.x-edge})));}
 function updateObject(p){if(p.modelId)world.updatePlacement(p);refreshFloor();}
 function blocked(p){return !!p.modelId&&overlapsTrigger(p,chapter,book);}
 function warnOverlap(){toast('애니메이션 발동 영역이 다른 모델과 겹칩니다. 빈 공간에 배치하세요.');}
 world.root.position.x=zoneFor(chapter.id).x;world.controls.target.set(world.root.position.x,0,0); world.camera.position.set(world.root.position.x,38,42); world.controls.update();
 const transform=new TransformControls(world.camera,world.renderer.domElement);
 world.scene.add(transform.getHelper());transform.setSize(.8);transform.setTranslationSnap(step);transform.setRotationSnap(Math.PI/12);transform.setScaleSnap(.1);
 // Edit a stable proxy: playback never drives the transform handle or camera.
 const proxy=new THREE.Object3D();world.scene.add(proxy);
 transform.addEventListener('dragging-changed',e=>{world.controls.enabled=!e.value;suppressSelection=true;if(e.value)showRanges(current());else clearRanges();if(!e.value){hooks.change();setTimeout(()=>suppressSelection=false,0);}});
 transform.addEventListener('objectChange',()=>{
   const p=current();if(!p)return;
   const scaled=[proxy.scale.x,proxy.scale.y,proxy.scale.z].sort((a,b)=>Math.abs(b-(p.scale||1))-Math.abs(a-(p.scale||1)))[0];
   const next={...p,...(mode==='scale'&&p.modelId?{scale:Math.max(.1,Math.min(8,Math.round((scaleGesture?scaleGesture.initial*Math.exp((scaleGesture.dx-scaleGesture.dy)*.01):scaled)*10)/10))}:{}),x:snapClamp(proxy.position.x-world.root.position.x,chapter.width/2-1),z:snapClamp(proxy.position.z,chapter.depth/2-1),y:Math.max(0,Math.min(40,Math.round(proxy.position.y/step)*step)),rotation:((Math.round(THREE.MathUtils.radToDeg(proxy.rotation.y)/15)*15+360)%720)-360};
   showRanges(next);if(!blocked(next))Object.assign(p,next);
   el('world-hint').textContent=blocked(next)?'발동 영역이 겹쳐 이동할 수 없습니다.':'격자에 맞춰 이동 중';
   proxy.position.set(p.x+world.root.position.x,p.y||0,p.z);proxy.rotation.y=THREE.MathUtils.degToRad(p.rotation);proxy.scale.setScalar(p.scale||1);updateObject(p);syncFields();refreshRoles();
 });
 let grid;function drawGrid(){if(grid){grid.parent.remove(grid);grid.geometry.dispose();grid.material.dispose();}const points=[];for(let x=Math.ceil(worldBounds.start/step)*step;x<=worldBounds.end;x+=step)points.push(x,.04,-worldBounds.depth/2,x,.04,worldBounds.depth/2);for(let z=-Math.floor(worldBounds.depth/2/step)*step;z<=worldBounds.depth/2;z+=step)points.push(worldBounds.start,.04,z,worldBounds.end,.04,z);grid=new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(points,3)),new THREE.LineBasicMaterial({color:'#9fac9c',transparent:true,opacity:.45}));grid.name='world-grid';world.scene.add(grid);}
 drawGrid();
 function snapClamp(v,max){return Math.max(-Math.floor(max/step)*step,Math.min(Math.floor(max/step)*step,Math.round(v/step)*step));}
 const ray=new THREE.Raycaster();const pointer=new THREE.Vector2();const ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);
 function groundPoint(e){const rect=world.renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,world.camera);const p=new THREE.Vector3();return ray.ray.intersectPlane(ground,p)?world.root.worldToLocal(p):null;}
 function clearRanges(){if(rangeLayer){world.scene.remove(rangeLayer);world.disposeTree(rangeLayer);rangeLayer=null;}}
 function showRanges(candidate){
   clearRanges();rangeLayer=new THREE.Group();rangeLayer.name='placement-ranges';world.scene.add(rangeLayer);
   const disc=(x,z,r,color,fill)=>{const mesh=new THREE.Mesh(fill?new THREE.CircleGeometry(r,64):new THREE.RingGeometry(Math.max(0,r-.08),r,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:fill?.12:.9,depthWrite:false,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.35,z);rangeLayer.add(mesh);};
   for(const zone of zones)for(const p of zone.chapter.placements)if(p.id!==candidate?.id){const r=reactionSize(p,zone.chapter);disc(zone.x+p.x,p.z,r,'#d56868',true);disc(zone.x+p.x,p.z,r,'#d56868',false);}
   if(!candidate||candidate.asset)return;const r=reactionSize(candidate,chapter),x=world.root.position.x+candidate.x,color=overlapsTrigger(candidate,chapter,book)?'#e55f5f':'#81c8a3';disc(x,candidate.z,r,color,true);disc(x,candidate.z,r,color,false);
   if(mode==='radius'&&candidate.modelId)for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const handle=new THREE.Mesh(new THREE.SphereGeometry(.35,12,8),new THREE.MeshBasicMaterial({color:'#f3d992',depthTest:false}));handle.position.set(x+dx*r,.5,candidate.z+dz*r);handle.userData.radiusHandle=true;handle.renderOrder=5;rangeLayer.add(handle);}
 }
 const canvas=world.renderer.domElement;
 const radiusDown=e=>{if(mode==='scale'&&current()?.modelId&&e.button===0)scaleGesture={x:e.clientX,y:e.clientY,dx:0,dy:0,initial:current().scale};if(mode!=='radius'||!current()?.modelId||e.button!==0)return;groundPoint(e);const hit=rangeLayer&&ray.intersectObjects(rangeLayer.children).find(h=>h.object.userData.radiusHandle);if(!hit)return;e.preventDefault();e.stopImmediatePropagation();radiusDrag={id:e.pointerId,before:current().radius};suppressSelection=true;world.controls.enabled=false;canvas.setPointerCapture(e.pointerId);};
 const radiusMove=e=>{if(scaleGesture&&mode==='scale'){scaleGesture.dx=e.clientX-scaleGesture.x;scaleGesture.dy=e.clientY-scaleGesture.y;}if(!radiusDrag||e.pointerId!==radiusDrag.id)return;e.preventDefault();e.stopImmediatePropagation();const p=current(),point=groundPoint(e);if(!p||!point)return;const radius=Math.max(.5,Math.min(20,Math.round(Math.hypot(point.x-p.x,point.z-p.z)/(chapter.reactionMultiplier??2)*10)/10)),next={...p,radius};showRanges(next);if(!blocked(next)){p.radius=radius;updateObject(p);syncFields();}el('world-hint').textContent=blocked(next)?'발동 범위가 겹쳐 더 늘릴 수 없습니다.':'발동 범위 '+reactionSize(p,chapter).toFixed(1)+' m';};
 const radiusUp=e=>{scaleGesture=null;if(!radiusDrag||e.pointerId!==radiusDrag.id)return;e.preventDefault();e.stopImmediatePropagation();const before=radiusDrag.before;radiusDrag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);world.controls.enabled=true;if(current()?.radius!==before)hooks.change();showRanges(current());setTimeout(()=>suppressSelection=false,0);};
 canvas.addEventListener('pointerdown',radiusDown,true);canvas.addEventListener('pointermove',radiusMove,true);canvas.addEventListener('pointerup',radiusUp,true);canvas.addEventListener('pointercancel',radiusUp,true);
 el('studio-world').ondragleave=e=>{if(!el('studio-world').contains(e.relatedTarget)){ghost.visible=false;clearRanges();}};
 const ghost=new THREE.Mesh(new THREE.BoxGeometry(2,2,2),new THREE.MeshBasicMaterial({color:'#5c9f83',transparent:true,opacity:.35,depthWrite:false}));ghost.visible=false;world.root.add(ghost);
 el('studio-world').ondragover=e=>{e.preventDefault();const p=groundPoint(e);ghost.visible=!!p&&!!dragModel;if(p){ghost.position.set(snapClamp(p.x,chapter.width/2-1),1,snapClamp(p.z,chapter.depth/2-1));const valid=Math.abs(p.x)<=chapter.width/2-1&&Math.abs(p.z)<=chapter.depth/2-1&&(dragModel?.tile||!overlapsTrigger({x:ghost.position.x,z:ghost.position.z,radius:2,scale:1,collisionRadius:.8},chapter,book));ghost.material.color.set(valid?'#5c9f83':'#ba5959');if(dragModel&&!dragModel.tile)showRanges({x:ghost.position.x,z:ghost.position.z,radius:2,scale:1,collisionRadius:.8});el('world-hint').textContent=valid?'배치 가능 · '+chapter.title:'배치 불가 · 범위가 겹치거나 챕터 밖입니다.';e.dataTransfer.dropEffect=valid?'copy':'none';}};
 el('studio-world').ondrop=e=>{e.preventDefault();ghost.visible=false;clearRanges();const point=groundPoint(e),payload=e.dataTransfer.getData('text/plain');if(payload.startsWith('otb-tile:')){if(point&&Math.abs(point.x)<=chapter.width/2-1&&Math.abs(point.z)<=chapter.depth/2-1)addTile(payload.slice(9),point);return;}const model=models.find(m=>m.id===payload);if(!point||!model||!eligible(model))return;if(Math.abs(point.x)>chapter.width/2-1||Math.abs(point.z)>chapter.depth/2-1)return toast('챕터 격자 안에 배치하세요.');addModel(model,point);};
 function addModel(model,point){if(chapter.placements.length>=60)return toast('챕터당 60개까지 배치할 수 있습니다.');const p={id:uid(),modelId:model.id,title:model.name,x:snapClamp(point.x,chapter.width/2-1),y:0,z:snapClamp(point.z,chapter.depth/2-1),scale:1,rotation:0,radius:2,collision:true,collisionRadius:.8,animation:model.kind==='glb'?'clip':'hop',clip:model.clips?.[0]||'',story:''};if(blocked(p))return warnOverlap();chapter.placements.push(p);if(chapter.placements.length===1)chapter.mainPlacementId=p.id;world.addPlacement(p);refreshFloor();selectObject(p.id);hooks.change();}
 app.querySelectorAll('[data-model]').forEach(card=>{card.ondragstart=e=>{const m=models.find(m=>m.id===card.dataset.model);if(!eligible(m)){e.preventDefault();return;}dragModel=m;e.dataTransfer.setData('text/plain',m.id);e.dataTransfer.effectAllowed='copy';};card.ondragend=()=>{ghost.visible=false;dragModel=null;clearRanges();};});
 const floorAssets=new Map([['arrow','화살표'],['leaves','나뭇잎'],['pocket-watch','회중시계'],['tea-cup','찻잔'],['open-book','펼친 책']]);
 for(const item of book.floorAssets||[])floorAssets.set(item.asset,item.name);
 for(const c of book.chapters)for(const item of c.floorDecals||[])if(!floorAssets.has(item.asset))floorAssets.set(item.asset,'등록 이미지');
 function addTile(asset,point){
   if(!floorAssets.has(asset))return;
   const decals=chapter.floorDecals??defaultDecals(chapter);if(decals.length>=100)return toast('이미지는 100개까지 배치할 수 있습니다.');
   chapter.floorDecals=decals;const p={id:uid(),asset,x:snapClamp(point.x,chapter.width/2-1),y:0,z:snapClamp(point.z,chapter.depth/2-1),width:3,height:3,rotation:0};decals.push(p);
   refreshFloor();selectObject(p.id);hooks.change();
 }
 function renderFloorAssets(){
   app.querySelector('.tile-tray').innerHTML=[...floorAssets].map(([asset,name])=>`<div class="floor-tile-card" draggable="true" data-floor-asset="${esc(asset)}"><div class="square-tile"><img draggable="false" src="${asset.startsWith('/uploads/')?esc(asset):'/floor-assets/'+asset+'.svg'}" alt="${esc(name)}"></div><span>${esc(name)}</span></div>`).join('');
   app.querySelectorAll('[data-floor-asset]').forEach(card=>{card.ondragstart=e=>{dragModel={tile:true};e.dataTransfer.setData('text/plain','otb-tile:'+card.dataset.floorAsset);e.dataTransfer.effectAllowed='copy';};card.ondragend=()=>{ghost.visible=false;dragModel=null;clearRanges();};});
 }
 renderFloorAssets();refreshFloor();
 el('upload-floor-asset').onchange=async e=>{const file=e.target.files[0];if(!file)return;if((book.floorAssets?.length||0)>=300){toast('등록 이미지는 도서당 300개까지 추가할 수 있습니다.');e.target.value='';return;}try{const body=new FormData();body.append('image',file);const result=await api('/api/floor/upload',{method:'POST',body});if(dead)return;const name=file.name.slice(0,200);(book.floorAssets??=[]).push({asset:result.url,name});floorAssets.set(result.url,name);renderFloorAssets();hooks.change();toast('바닥 이미지를 등록했습니다. 임시 저장하면 목록도 보관됩니다.');}catch(error){toast(error.message);}e.target.value='';};
 el('asset-search').oninput=e=>app.querySelectorAll('[data-model]').forEach(c=>c.hidden=!c.dataset.name.includes(e.target.value.toLowerCase()));
 let roleMarkers;
 function refreshRoles(){
   el('placement-target').textContent='배치 대상: '+chapter.title;
   app.querySelectorAll('[data-count-chapter]').forEach(label=>{const c=book.chapters.find(c=>c.id===label.dataset.countChapter);label.textContent=c.placements.length?`모델 ${c.placements.length}개`:'모델 없음';});
   const ordered=[...chapter.placements].sort((a,b)=>Number(b.id===mainModel(chapter)?.id)-Number(a.id===mainModel(chapter)?.id));
   el('chapter-model-list').innerHTML=ordered.map(p=>{const src=app.querySelector(`[data-thumb="${p.modelId}"] img`)?.src;return `<button class="chapter-model-item ${p.id===selected?'active':''}" data-select-model="${p.id}"><span class="chapter-model-thumb" data-role-thumb="${p.modelId}">${src?`<img src="${src}" alt="">`:'◇'}</span><span>${esc(p.title)}<small>${p.id===mainModel(chapter)?.id?'★ 메인':'• 보조'}</small></span></button>`;}).join('')||'<p class="panel-note">모델을 배치하면 첫 모델이 메인이 됩니다.</p>';
   el('chapter-model-list').querySelectorAll('[data-select-model]').forEach(button=>button.onclick=()=>selectObject(button.dataset.selectModel));
   if(roleMarkers){world.scene.remove(roleMarkers);world.disposeTree(roleMarkers);}roleMarkers=new THREE.Group();roleMarkers.name='model-role-markers';world.scene.add(roleMarkers);
   for(const zone of zones)for(const p of zone.chapter.placements){const isMain=mainModel(zone.chapter)?.id===p.id;let geometry;if(isMain){const shape=new THREE.Shape();for(let i=0;i<10;i++){const angle=i*Math.PI/5+Math.PI/2,r=i%2?.24:.55;const x=Math.cos(angle)*r,y=Math.sin(angle)*r;i?shape.lineTo(x,y):shape.moveTo(x,y);}shape.closePath();geometry=new THREE.ShapeGeometry(shape);}else geometry=new THREE.CircleGeometry(.15,16);const marker=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:isMain?'#d0a14c':'#6d8a76',side:THREE.DoubleSide,depthTest:false}));marker.rotation.x=-Math.PI/2;marker.position.set(zone.x+p.x+1.3,.4,p.z+1.3);marker.renderOrder=4;roleMarkers.add(marker);}
 }
 const syncThumbnail=e=>{const source=e.target;if(source.tagName!=='IMG'||!source.closest('[data-thumb]'))return;app.querySelectorAll(`[data-role-thumb="${source.closest('[data-thumb]').dataset.thumb}"]`).forEach(target=>{const image=document.createElement('img');image.alt='';image.src=source.src;target.replaceChildren(image);});};app.addEventListener('load',syncThumbnail,true);
 function selectObject(id){selected=id;hooks.select(id);const p=current();transform.detach();if(p){proxy.position.set(p.x+world.root.position.x,p.y||0,p.z);proxy.rotation.set(0,THREE.MathUtils.degToRad(p.rotation),0);proxy.scale.setScalar(p.scale||1);if(mode!=='radius'&&(mode!=='scale'||p.modelId))transform.attach(proxy);}properties();refreshRoles();if(mode==='radius')showRanges(p);}
 const num=(label,key,value,min,max,increment=.1)=>`<label>${label}<input name="${key}" type="number" value="${value}" min="${min}" max="${max}" step="${key==='radius'?'any':increment}" required></label>`;
 function properties(){const p=current();if(p?.asset){floorProperties(p);return;}if(!p){el('object-properties').innerHTML='<div class="world-empty">월드에서 모델 또는 이미지를 선택하세요.<br><br>새 챕터는 빈 월드입니다. 왼쪽 보관함에서 모델을 끌어 놓으세요.</div>';return;}const model=models.find(m=>m.id===p.modelId);el('object-properties').innerHTML=`<form id="object-form"><div class="model-role">${mainModel(chapter)?.id===p.id?'★ 메인 · 화살표와 본문 연결':'• 보조 · 접근 애니메이션'}</div>${mainModel(chapter)?.id!==p.id?'<button type="button" id="make-main">메인 모델로 지정</button>':''}<label>장면 속 이름<input name="title" value="${esc(p.title)}" maxlength="200" required></label><h3>위치 · 격자에 맞춰 이동</h3><div class="axis-inputs">${num('X','x',p.x,-Math.floor((chapter.width/2-1)/step)*step,Math.floor((chapter.width/2-1)/step)*step,step)}${num('Y 높이','y',p.y||0,0,40,step)}${num('Z','z',p.z,-Math.floor((chapter.depth/2-1)/step)*step,Math.floor((chapter.depth/2-1)/step)*step,step)}</div>${num('방향 (도)','rotation',p.rotation,-360,360,15)}${num('크기 배율','scale',p.scale,.1,8)}<h3>접근 애니메이션</h3>${model.kind!=="glb"?`<label>기본 동작<select name="animation">${Object.entries({hop:"폴짝 뛰기",spin:"회전",float:"둥실 떠오르기",sway:"흔들기",none:"동작 없음"}).map(([value,label])=>`<option value="${value}" ${p.animation===value?"selected":""}>${label}</option>`).join("")}</select></label>`:eligible(model)?`<label>재생할 동작<select name="clip">${model.clips.map(c=>`<option ${p.clip===c?'selected':''} value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label>`:'<p class="legacy-note">기존 모델입니다. 뼈대 애니메이션 모델로 교체하려면 새 모델을 배치하세요.</p>'}<button type="button" id="play-clip">동작 재생 / 정지</button>${num('발동 반경 (m)','radius',Number(reactionSize(p,chapter).toFixed(2)),Number(reactionSize({...p,radius:.5},chapter).toFixed(2)),20*(chapter.reactionMultiplier??2))}<p id="actual-radius">실제 접근 범위 ${reactionSize(p,chapter).toFixed(1)} m</p><h3>충돌</h3><label class="inline-check"><input name="collision" type="checkbox" ${p.collision!==false?'checked':''}>캐릭터 통과 막기</label>${num('충돌 반경','collisionRadius',p.collisionRadius??.8,.1,20)}<div class="object-actions"><button type="button" id="duplicate-object" ${eligible(model)?'':'disabled'}>복제</button><button type="button" id="delete-object">삭제</button></div></form>`;
 const form=el('object-form');form.onsubmit=e=>e.preventDefault();form.oninput=form.onchange=e=>{const input=e.target;if(!input.name||!input.checkValidity())return;let value=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;if(['x','y','z'].includes(input.name))value=Math.round(value/step)*step;if(input.name==='radius')value=value/(chapter.reactionMultiplier??2);const next={...p,[input.name]:value};if(['x','z','scale','radius','collision','collisionRadius'].includes(input.name)&&blocked(next)){input.type==='checkbox'?input.checked=p[input.name]:input.value=input.name==='radius'?Number(reactionSize(p,chapter).toFixed(2)):p[input.name];warnOverlap();return;}p[input.name]=value;if(input.name==='clip')p.animation='clip';proxy.position.set(p.x+world.root.position.x,p.y||0,p.z);proxy.rotation.y=THREE.MathUtils.degToRad(p.rotation);proxy.scale.setScalar(p.scale||1);updateObject(p);if(mode==='radius')showRanges(p);if(e.type==='change')hooks.change();syncFields(e.type==='input'?input:null);refreshRoles();};
 if(el('make-main'))el('make-main').onclick=()=>{chapter.mainPlacementId=p.id;refreshFloor();selectObject(p.id);hooks.change();};
 el('play-clip').onclick=()=>{world.previewId=world.previewId===p.id?null:p.id;};
 el('delete-object').onclick=()=>{
   const remove=replacement=>{chapter.placements.splice(chapter.placements.indexOf(p),1);if(chapter.mainPlacementId===p.id)chapter.mainPlacementId=replacement??null;const o=world.objects.find(o=>o.p.id===p.id);for(const obj of [o?.group,o?.halo,o?.collisionHalo])if(obj){world.root.remove(obj);world.disposeTree(obj);}world.objects=world.objects.filter(o=>o.p.id!==p.id);refreshFloor();selectObject(null);hooks.change();};
   const alternatives=chapter.placements.filter(o=>o.id!==p.id);
   if(mainModel(chapter)?.id===p.id&&alternatives.length){const dialog=modal(`<h2>메인 모델 삭제</h2><p>새 메인 모델을 선택하면 기존 모델을 삭제합니다.</p><form><label>대체 메인 모델<select name="replacement" required><option value="">모델 선택</option>${alternatives.map(o=>`<option value="${o.id}">${esc(o.title)}</option>`).join('')}</select></label><div class="modal-actions"><button type="button" class="cancel-main-delete">취소</button><button type="submit">선택하고 삭제</button></div></form>`);dialog.querySelector('.cancel-main-delete').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const replacement=new FormData(e.target).get('replacement');if(!alternatives.some(o=>o.id===replacement))return;remove(replacement);dialog.close();};}else remove();
 };

 el('duplicate-object').onclick=()=>{if(chapter.placements.length>=60)return;const copy={...p,id:uid()};const spots=[];for(let x=-Math.floor((chapter.width/2-1)/step)*step;x<=chapter.width/2-1;x+=step)for(let z=-Math.floor((chapter.depth/2-1)/step)*step;z<=chapter.depth/2-1;z+=step)spots.push({x,z});spots.sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z));const spot=spots.find(v=>!blocked({...copy,...v}));if(!spot)return toast('발동 영역이 겹치지 않는 빈자리가 없습니다.');Object.assign(copy,spot);chapter.placements.push(copy);world.addPlacement(copy);refreshFloor();selectObject(copy.id);hooks.change();};
 }
 function floorProperties(p){
   el('object-properties').innerHTML=`<form id="object-form"><h3>바닥 이미지 · 위치와 방향</h3><div class="axis-inputs">${num('X','x',p.x,-chapter.width/2+1,chapter.width/2-1,step)}${num('Y 높이','y',p.y||0,0,40,step)}${num('Z','z',p.z,-chapter.depth/2+1,chapter.depth/2-1,step)}</div>${num('방향 (도)','rotation',p.rotation,-360,360,15)}${num('가로 크기','width',p.width,.2,30)}${num('세로 크기','height',p.height,.2,30)}<button type="button" id="delete-floor-object">이미지 삭제</button></form>`;
   const form=el('object-form');form.onsubmit=e=>e.preventDefault();form.oninput=form.onchange=e=>{const input=e.target;if(!input.name||!input.checkValidity())return;let value=Number(input.value);if(['x','y','z'].includes(input.name))value=Math.round(value/step)*step;if(input.name==='x')value=snapClamp(value,chapter.width/2-1);if(input.name==='z')value=snapClamp(value,chapter.depth/2-1);p[input.name]=value;proxy.position.set(p.x+world.root.position.x,p.y||0,p.z);proxy.rotation.y=THREE.MathUtils.degToRad(p.rotation);refreshFloor();syncFields(e.type==='input'?input:null);if(e.type==='change')hooks.change();};
   el('delete-floor-object').onclick=()=>{chapter.floorDecals.splice(chapter.floorDecals.indexOf(p),1);refreshFloor();selectObject(null);hooks.change();};
 }
 function syncFields(editing=null){const p=current();if(!p)return;for(const key of ['x','y','z','rotation','scale','radius']){const input=el('object-form')?.elements.namedItem(key);if(input&&input!==editing)input.value=key==='radius'?Number(reactionSize(p,chapter).toFixed(2)):(p[key]??0);}const radiusInput=el('object-form')?.elements.namedItem('radius');if(radiusInput&&p.modelId)radiusInput.min=Number(reactionSize({...p,radius:.5},chapter).toFixed(2));if(el('actual-radius'))el('actual-radius').textContent='실제 접근 범위 '+reactionSize(p,chapter).toFixed(1)+' m';if(mode==='radius'&&p.modelId)el('world-hint').textContent='발동 범위 '+reactionSize(p,chapter).toFixed(1)+' m';}

 function setMode(next){if(radiusDrag)radiusUp({pointerId:radiusDrag.id,preventDefault(){},stopImmediatePropagation(){}});if(transform.dragging)transform.pointerUp({button:0});scaleGesture=null;world.controls.enabled=true;mode=next;clearRanges();for(const [id,value] of [['tool-move','translate'],['tool-rotate','rotate'],['tool-scale','scale'],['tool-radius','radius']])el(id).classList.toggle('active',mode===value);transform.detach();if(next!=='radius'){transform.setMode(next);transform.showX=next!=='rotate';transform.showZ=next!=='rotate';}selectObject(selected);el('world-hint').textContent=mode==='translate'?'왼쪽 드래그: 회전 · 오른쪽 드래그: 화면 이동 · 휠: 확대':'같은 도구 또는 Esc: 이동 모드로 돌아가기';}
 function toggleMode(next){setMode(mode===next?'translate':next);}
 el('tool-move').onclick=()=>setMode('translate');el('tool-rotate').onclick=()=>setMode('rotate');el('tool-scale').onclick=()=>toggleMode('scale');el('tool-radius').onclick=()=>toggleMode('radius');el('grid-step').onchange=e=>{step=Number(e.target.value);transform.setTranslationSnap(step);drawGrid();properties();};
 el('scene-reset').onclick=()=>{stopTravel();world.controls.target.set(world.root.position.x,0,0);world.camera.position.set(world.root.position.x,38,42);world.controls.update();};
 for(const [id,fn] of Object.entries({'back-library':hooks.back,'edit-book':hooks.editBook,'add-chapter':hooks.addChapter,'preview-client':()=>{if(readerMode)return;stopTravel();transform.detach();try{readerMode=inlineReader(app.querySelector(".world-workspace"),world,book,chapter,models,()=>{readerMode=null;selectObject(selected);});}catch(error){toast(error.message);selectObject(selected);}},'new-model':hooks.addModel,save:hooks.save,publish:hooks.publish,undo:hooks.undo,redo:hooks.redo}))el(id).onclick=fn;
 let draggedChapter=null;
 const chapterList=app.querySelector('.world-chapter-tabs');
 const clearChapterDrag=()=>{draggedChapter=null;chapterList.querySelectorAll('.dragging,.drop-before,.drop-after').forEach(row=>row.classList.remove('dragging','drop-before','drop-after'));};
 app.querySelectorAll('[data-chapter-edit]').forEach(button=>button.onclick=()=>hooks.editChapter(button.dataset.chapterEdit));
 app.querySelectorAll('[data-chapter-drag]').forEach(handle=>{
   handle.ondragstart=e=>{draggedChapter=handle.dataset.chapterDrag;e.dataTransfer.setData('application/x-otb-chapter',draggedChapter);e.dataTransfer.effectAllowed='move';handle.closest('.chapter-row').classList.add('dragging');};
   handle.ondragend=clearChapterDrag;
   handle.onkeydown=e=>{if(!e.altKey||!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const ids=book.chapters.map(c=>c.id),index=ids.indexOf(handle.dataset.chapterDrag),next=index+(e.key==='ArrowUp'?-1:1);if(next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];hooks.reorderChapters(ids);};
 });
 chapterList.ondragover=e=>{if(!draggedChapter)return;e.preventDefault();e.dataTransfer.dropEffect='move';const row=e.target.closest('[data-chapter-row]');chapterList.querySelectorAll('.drop-before,.drop-after').forEach(r=>r.classList.remove('drop-before','drop-after'));if(row&&row.dataset.chapterRow!==draggedChapter)row.classList.add(e.clientY<row.getBoundingClientRect().top+row.offsetHeight/2?'drop-before':'drop-after');if(e.clientY<chapterList.getBoundingClientRect().top+28)chapterList.scrollTop-=12;if(e.clientY>chapterList.getBoundingClientRect().bottom-28)chapterList.scrollTop+=12;};
 chapterList.ondrop=e=>{if(!draggedChapter)return;e.preventDefault();e.stopPropagation();const row=e.target.closest('[data-chapter-row]'),ids=book.chapters.map(c=>c.id);if(row?.dataset.chapterRow===draggedChapter){clearChapterDrag();return;}const next=ids.filter(id=>id!==draggedChapter);let index=row?next.indexOf(row.dataset.chapterRow)+(e.clientY>=row.getBoundingClientRect().top+row.offsetHeight/2?1:0):next.length;next.splice(index,0,draggedChapter);clearChapterDrag();if(next.some((id,i)=>id!==ids[i]))hooks.reorderChapters(next);};
 app.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>changeChapter(b.dataset.chapter));app.querySelectorAll('[data-model-edit]').forEach(b=>b.onclick=()=>hooks.editModel(models.find(m=>m.id===b.dataset.modelEdit)));
 const keys=e=>{if(readerMode)return;if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable)return;const key=e.key.toLowerCase();if(e.ctrlKey||e.metaKey){if(key==='z'){e.preventDefault();e.shiftKey?hooks.redo():hooks.undo();}return;}if(e.altKey||e.repeat)return;if(!['w','e','s','r','escape'].includes(key))return;e.preventDefault();if(key==='w')setMode('translate');if(key==='e')setMode('rotate');if(key==='s')toggleMode('scale');if(key==='r')toggleMode('radius');if(key==='escape'){if(mode==='translate')selectObject(null);else setMode('translate');}};document.addEventListener('keydown',keys);
 selectObject(selected);
 const disposeThumbnails=thumbnails(app,models);
 const disposeOrientation=orientationWidget(app.querySelector(".world-workspace"),world);
 app.querySelector(".view-orientation").addEventListener("pointerdown",stopTravel);
 // Keep every chapter in one scene; only the editor context and camera change.
 const remember=()=>chapterScenes.set(chapter.id,{root:world.root,objects:world.objects,floorArt:world.floorArt});
 remember();const activeChapter=chapter;
 for(const zone of zones){if(zone.chapter.id===activeChapter.id)continue;world.root=new THREE.Group();world.root.position.x=zone.x;world.scene.add(world.root);world.objects=[];world.chapter=zone.chapter;world.floorArt=floorArt(world.root,zone.chapter);for(const p of zone.chapter.placements)world.addPlacement(p);chapterScenes.set(zone.chapter.id,{root:world.root,objects:world.objects,floorArt:world.floorArt});}
 Object.assign(world,chapterScenes.get(activeChapter.id));world.chapter=activeChapter;
 for(const item of [...world.root.children])if(item.userData.worldGround||item.userData.groundDecoration){world.root.remove(item);world.disposeTree(item);}
 terrain(world.scene,{width:worldBounds.end-worldBounds.start,depth:worldBounds.depth,placements:[]},(worldBounds.start+worldBounds.end)/2,[],true);
 world.pickObjects=()=>[...chapterScenes.values()].flatMap(c=>c.root.children.filter(o=>o.userData.placementId));
 world.pickFloorObjects=()=>[...chapterScenes.values()].flatMap(c=>c.root.children.flatMap(g=>g.children.filter(o=>o.userData.floorDecalId)));
 
 world.camera.far=Math.max(350,book.chapters.reduce((n,c)=>n+c.width,0)+150);world.camera.updateProjectionMatrix();
 function stopTravel(){cancelAnimationFrame(cameraFrame);cameraFrame=0;world.controls.enabled=true;world.renderer.domElement.style.pointerEvents='';app.querySelector('.world-workspace').dataset.travelling='false';}
 function changeChapter(id,travel=true){
   if(readerMode||id===chapter.id)return;const next=book.chapters.find(c=>c.id===id);if(!next)return;
   stopTravel();remember();selectObject(null);chapter=next;Object.assign(world,chapterScenes.get(id));world.chapter=chapter;world.previewId=null;world.root.add(ghost);ghost.visible=false;
   hooks.chapter(id);properties();refreshRoles();
   app.querySelectorAll('[data-chapter-row]').forEach(row=>row.classList.toggle('active',row.dataset.chapterRow===id));
   if(!travel)return;
   const fromTarget=world.controls.target.clone(),fromPosition=world.camera.position.clone(),toTarget=new THREE.Vector3(world.root.position.x+(mainModel(chapter)?.x||0),mainModel(chapter)?.y||0,mainModel(chapter)?.z||0),toPosition=toTarget.clone().add(fromPosition.clone().sub(fromTarget));
   const started=performance.now(),duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:850;
   world.controls.enabled=false;world.renderer.domElement.style.pointerEvents='none';app.querySelector('.world-workspace').dataset.travelling='true';
   const animate=now=>{const t=duration?Math.min(1,(now-started)/duration):1,ease=t*t*(3-2*t);world.controls.target.lerpVectors(fromTarget,toTarget,ease);world.camera.position.lerpVectors(fromPosition,toPosition,ease);world.controls.update();if(t<1)cameraFrame=requestAnimationFrame(animate);else stopTravel();};
   cameraFrame=requestAnimationFrame(animate);
 }
 return {world,dispose(){canvas.removeEventListener('pointerdown',radiusDown,true);canvas.removeEventListener('pointermove',radiusMove,true);canvas.removeEventListener('pointerup',radiusUp,true);canvas.removeEventListener('pointercancel',radiusUp,true);clearRanges();app.removeEventListener('load',syncThumbnail,true);stopTravel();dead=true;readerMode?.close();disposeOrientation();disposeThumbnails();document.removeEventListener('keydown',keys);transform.dispose();world.dispose();}};
}

// A single renderer supplies real model thumbnails, avoiding one WebGL context per card.
function thumbnails(app,models){
 let dead=false,frame;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(180,130);renderer.setPixelRatio(1);
 const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight('#ffffff','#536457',3));const sun=new THREE.DirectionalLight('#ffffff',3);sun.position.set(3,5,4);scene.add(sun);
 const camera=new THREE.PerspectiveCamera(35,180/130,.1,100);camera.position.set(3,2.6,4);camera.lookAt(0,1,0);
 const loader=new GLTFLoader();let active=null;const entries=[];
 const render=entry=>{entry.group.visible=true;renderer.render(scene,camera);entry.image.src=renderer.domElement.toDataURL();entry.group.visible=false;};
 (async()=>{for(const m of models){if(dead)break;const target=app.querySelector(`[data-thumb="${m.id}"]`);if(!target)continue;try{const group=new THREE.Group();let mixer=null;if(m.kind==='glb'){const gltf=await loader.loadAsync(m.url);if(dead){gltf.scene.traverse(o=>{o.geometry?.dispose();});break;}const bounds=new THREE.Box3().setFromObject(gltf.scene),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),scale=2/Math.max(size.x,size.y,size.z,.01);gltf.scene.scale.setScalar(scale);gltf.scene.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);group.add(gltf.scene);if(gltf.animations.length){mixer=new THREE.AnimationMixer(gltf.scene);mixer.clipAction(gltf.animations[0]).play();}}else group.add(makeModel(m.kind,m.color));group.visible=false;scene.add(group);const image=document.createElement('img');image.alt=m.name;image.draggable=false;target.append(image);const entry={group,image,mixer};entries.push(entry);render(entry);target.parentElement.onmouseenter=()=>active=entry;target.parentElement.onmouseleave=()=>active=null;}catch{target.textContent='미리보기 불러오기 실패';}}})();
 let last=0;function tick(t){if(dead)return;if(active){active.mixer?.update(Math.min((t-last)/1000,.05));render(active);}last=t;frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);
 return()=>{dead=true;cancelAnimationFrame(frame);scene.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});renderer.dispose();};
}







