export const cases=[];
const add=(group,id,title,given,when,then,run,data={})=>cases.push({group,id,title,given,when,then,run,data});

add('client-basic','C01','첫 화면과 실제 3D 장면','공개된 도서가 있는 새 브라우저','사용자 첫 화면에 접속한다','책 제목과 시작 버튼 및 3D 화면이 보인다',async(p,h)=>{await h.home();await h.visible('#start-button');await h.visible('#world canvas');h.check(await p.locator('.hero-copy h2').innerText(),'책 제목');h.eq(await p.locator('.world-error').count(),0);});
add('client-basic','C02','처음 탐험할 때 사용 안내','탐험 기록이 없는 사용자','책 속으로 들어가기를 누른다','사용 안내가 열리고 닫은 뒤 탐험할 수 있다',async(p,h)=>{await h.home();await p.locator('#start-button').click();await h.visible('dialog');await h.contains('dialog','정해진 속도는 없어요.');await p.getByRole('button',{name:'닫기',exact:true}).click();await h.visible('#map-button');});
add('client-basic','C03','반복 방문 시 안내를 중복 표시하지 않음','사용 안내를 이미 본 사용자','책 속으로 다시 들어간다','안내창 없이 탐험을 시작한다',async(p,h)=>{await h.home();await p.evaluate(()=>localStorage.setItem('otb-reader',JSON.stringify({tutorial:true})));await p.reload();await p.locator('#start-button').click();await h.visible('#map-button');h.eq(await p.locator('dialog[open]').count(),0);});
add('client-basic','C04','도서 선택과 표지 정보','사용자가 첫 화면에 있다','책장에서 오즈의 마법사를 선택한다','선택한 책 제목과 작가 및 장면 수가 표시된다',async(p,h)=>{await h.home();await p.locator('#library-button').click();h.eq(await p.locator('[data-book]').count(),2);await p.locator('[data-book="oz"]').click();await h.waitText('.hero-copy h2','오즈의 마법사');await h.contains('.book-credit','3개의 장면');h.check(p.url().includes('book=oz'),'선택한 책 URL');});
add('client-basic','C05','사용 안내의 키보드 닫기와 초점 복귀','첫 화면에서 안내 버튼에 초점을 둔다','안내를 열고 Escape를 누른다','안내가 닫히고 원래 버튼으로 초점이 돌아온다',async(p,h)=>{await h.home();await p.locator('#help-button').click();await h.visible('dialog');await p.keyboard.press('Escape');h.eq(await p.locator('dialog[open]').count(),0);h.eq(await p.evaluate(()=>document.activeElement?.id),'help-button');});
add('client-basic','C06','소리 켜기와 끄기','사용자 화면에서 소리가 꺼져 있다','소리 버튼을 두 번 누른다','버튼의 이름과 켜짐 상태가 순서대로 바뀐다',async(p,h)=>{await h.home();await p.locator('#sound-button').click();h.eq(await p.locator('#sound-button').getAttribute('aria-pressed'),'true');h.eq(await p.locator('#sound-button').getAttribute('aria-label'),'소리 끄기');await p.locator('#sound-button').click();h.eq(await p.locator('#sound-button').getAttribute('aria-pressed'),'false');});
add('client-basic','C07','첫 챕터의 이전 이동 제한','첫 챕터에 접속한 사용자','챕터 이동 버튼을 확인한다','이전 버튼은 비활성이고 다음 버튼은 활성이다',async(p,h)=>{await h.explore('alice','alice-1');h.check(await p.locator('#prev-chapter').isDisabled(),'이전 비활성');h.check(!(await p.locator('#next-chapter').isDisabled()),'다음 활성');});
add('client-basic','C08','마지막 챕터의 다음 이동 제한','마지막 챕터에 접속한 사용자','챕터 이동 버튼을 확인한다','다음 버튼은 비활성이고 이전 버튼은 활성이다',async(p,h)=>{await h.explore('alice','alice-6');h.check(await p.locator('#next-chapter').isDisabled(),'다음 비활성');h.check(!(await p.locator('#prev-chapter').isDisabled()),'이전 활성');});
add('client-navigation','C09','다음 챕터와 이전 챕터 이동','첫 챕터에 있는 사용자','다음 버튼을 누른 뒤 이전 버튼을 누른다','장면 이름과 주소가 각각 둘째 및 첫째 챕터로 바뀐다',async(p,h)=>{await h.explore('alice','alice-1');await p.locator('#next-chapter').click();await h.waitText('#map-button','작아지는 문');h.check(p.url().includes('chapter=alice-2'),'둘째 URL');await p.locator('#prev-chapter').click();await h.waitText('#map-button','흰 토끼');});
add('client-navigation','C10','마지막 방문 챕터 이어 읽기','셋째 챕터를 방문해 기록이 저장되었다','홈으로 돌아가 책 속으로 들어간다','셋째 챕터부터 이어서 시작한다',async(p,h)=>{await h.explore('alice','alice-1');await p.locator('#map-button').click();await p.locator('[data-chapter="2"]').click();await h.waitText('#map-button','버섯 숲');await p.waitForFunction(()=>JSON.parse(localStorage.getItem('otb-reader')||'{}').alice?.chapter==='alice-3');await h.home();await p.locator('#start-button').click();await h.waitText('#map-button','버섯 숲');});
add('client-navigation','C11','잘못된 책 주소에서 복구','존재하지 않는 책 식별자가 주소에 있다','사용자 화면을 연다','오류 없이 첫 공개 도서를 표시한다',async(p,h)=>{await h.home('?book=unknown-qa');await h.waitText('.hero-copy h2','이상한 나라의 앨리스');});
add('client-navigation','C12','잘못된 챕터 주소에서 복구','올바른 책과 존재하지 않는 챕터 주소','사용자 화면을 연다','첫 챕터를 탐험할 수 있다',async(p,h)=>{await h.explore('alice','unknown-qa');await h.waitText('#map-button','흰 토끼');});
add('client-navigation','C13','지도에서 현재 챕터 재선택','둘째 챕터 탐험 중이다','지도에서 같은 챕터를 다시 선택한다','지도는 닫히고 장면과 주소가 유지된다',async(p,h)=>{await h.explore('alice','alice-2');await p.locator('#map-button').click();await p.locator('[data-chapter="1"]').click();h.eq(await p.locator('dialog[open]').count(),0);h.check(p.url().includes('alice-2'),'현재 챕터 유지');await h.visible('#world canvas');});
add('client-navigation','C14','글귀 페이지 앞뒤 이동과 끝 경계','첫 챕터 메인 모델 근처에 도착했다','글귀를 끝까지 넘긴 뒤 한 페이지 돌아간다','글귀가 바뀌고 첫 페이지와 마지막 페이지의 이동이 제한된다',async(p,h)=>{await h.explore('alice','alice-1');await h.visible('.floor-reading-controls');h.check(await p.locator('#floor-prev').isDisabled(),'첫 페이지 이전 제한');const first=await p.locator('#floor-accessible').innerText();let n=0;while(!(await p.locator('#floor-next').isDisabled())&&n++<50)await p.locator('#floor-next').click();h.check(n>0&&n<50,'여러 페이지와 마지막 제한');const last=await p.locator('#floor-accessible').innerText();h.check(first!==last,'서로 다른 본문');await p.locator('#floor-prev').click();h.check(!(await p.locator('#floor-next').isDisabled()),'뒤로 간 후 다음 활성');});
add('client-navigation','C15','모델에서 멀어지면 독서 창 숨김','메인 모델 근처에서 글귀가 보인다','아래 방향키를 눌러 충분히 멀어진다','글귀가 숨겨지고 이동을 계속할 수 있다',async(p,h)=>{await h.explore('alice','alice-1');await h.visible('.floor-reading-controls');await p.locator('#world canvas').focus();await p.keyboard.down('ArrowDown');try{await p.locator('.floor-reading-controls').waitFor({state:'hidden',timeout:12000});}finally{await p.keyboard.up('ArrowDown');}await h.visible('#world canvas');});
add('client-navigation','C16','도서 전환 후 다른 책의 첫 장면','앨리스 탐험 중이다','책장에서 오즈를 고르고 탐험을 시작한다','오즈의 첫 챕터와 해당 책의 지도를 표시한다',async(p,h)=>{await h.explore('alice','alice-3');await p.locator('#library-button').click();await p.locator('[data-book="oz"]').click();await p.locator('#start-button').click();await h.waitText('#map-button','노란 벽돌');await h.visible('dialog');await h.closeDialogs();await p.locator('#map-button').click();h.eq(await p.locator('[data-chapter]').count(),3);});

for(const [i,book,chapter,title] of [[1,'alice','alice-1','흰 토끼를 따라서'],[2,'alice','alice-2','작아지는 문, 커지는 세계'],[3,'alice','alice-3','버섯 숲의 수수께끼'],[4,'alice','alice-4','끝나지 않는 티 파티'],[5,'alice','alice-5','장미 정원의 여왕'],[6,'alice','alice-6','꿈에서 깨어나는 시간'],[7,'oz','oz-1','노란 벽돌 길'],[8,'oz','oz-2','함께 걷는 숲'],[9,'oz','oz-3','집으로 가는 마음']])add('client-chapters','C'+(16+i),`공개 챕터 직접 접속: ${title}`,`${book}의 ${chapter}가 공개되어 있다`,'해당 챕터 주소로 접속하고 독서 창을 확인한다','챕터 제목과 비어 있지 않은 본문 및 3D 장면을 표시한다',async(p,h)=>{const d=h.data;await h.explore(d.book,d.chapter);await h.waitText('#map-button',d.title);await h.visible('.floor-reading-controls');await h.contains('#floor-title',d.title);h.check((await p.locator('#floor-accessible').innerText()).trim().length>0,'본문 존재');await h.visible('#world canvas');},{book,chapter,title});

for(const [i,value]of ['{broken','null','[]','"text"'].entries())add('client-recovery','R'+(i+1),`손상된 방문 기록 복구 ${i+1}`,'브라우저 방문 기록이 올바른 형식이 아니다','사용자 화면을 열고 탐험을 시작한다','화면이 멈추지 않고 첫 챕터를 탐험할 수 있다',async(p,h)=>{await p.addInitScript(v=>localStorage.setItem('otb-reader',v),h.data.value);await h.home();await p.locator('#start-button').click();await h.visible('#map-button');},{value});
add('client-recovery','R05','책장 요청 실패 후 재시도','책장 응답이 일시적으로 실패한다','오류 화면에서 다시 시도를 누른다','오류 안내 후 정상 첫 화면으로 복구한다',async(p,h)=>{let fail=true;await p.route('**/api/library',r=>fail?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'QA 일시 장애'})}):r.continue());await p.goto(h.base+'/client/');await h.visible('#retry');await h.contains('h1','책장을 불러오지 못했어요.');fail=false;await p.locator('#retry').click();await h.visible('#start-button');});
add('client-recovery','R06','공개 도서가 없는 책장','공개 도서 목록이 비어 있다','사용자 화면에 접속한다','새로운 이야기를 준비한다는 안내가 보인다',async(p,h)=>{await p.route('**/api/library',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({books:[],models:[]})}));await p.goto(h.base+'/client/');await h.waitText('h1','새로운 이야기를 준비하고 있어요.');h.eq(await p.locator('#start-button').count(),0);});
add('client-recovery','R07','3D 미지원 브라우저의 본문 대안','브라우저가 3D 그래픽을 지원하지 않는다','사용자 화면에서 이야기 읽기를 누른다','3D 오류 안내와 함께 본문 및 원작 링크를 읽을 수 있다',async(p,h)=>{await p.addInitScript(()=>{const f=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...args){return /webgl/.test(t)?null:f.call(this,t,...args);};});await h.home();await h.visible('#fallback-read');await p.locator('#fallback-read').click();await h.visible('.reading-text');h.check((await p.locator('.reading-text').innerText()).length>10,'대체 본문');h.eq(await p.locator('.source-note a').getAttribute('rel'),'noopener noreferrer');});
add('client-recovery','R08','저장 공간 쓰기 실패 안내','브라우저가 방문 기록 저장을 거부한다','처음 탐험을 시작한다','탐험을 유지하면서 저장 불가 안내를 표시한다',async(p,h)=>{await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('QA quota','QuotaExceededError');};});await h.home();await p.locator('#start-button').click();await h.visible('#map-button');await h.waitText('#toast','저장할 수 없습니다');});
add('client-recovery','R09','응답이 느릴 때 중복 진입 방지','책장 응답이 대기 중이다','사용자가 초기 로딩 상태를 확인한다','로딩을 알리고 응답이 끝나면 시작 버튼이 표시된다',async(p,h)=>{let release;const gate=new Promise(r=>release=r);await p.route('**/api/library',async r=>{await gate;await r.continue();});await p.goto(h.base+'/client/',{waitUntil:'domcontentloaded'});await p.locator('#app[aria-busy="true"]').waitFor({state:'attached'});release();await h.visible('#start-button');});

add('admin-shelf','A01','관리자 도서 보관함','로컬 관리자 화면에 접속한다','도서 목록과 저장 및 공개 버튼을 확인한다','기존 책 2권과 검색 및 상태 필터가 표시된다',async(p,h)=>{await h.admin();h.eq(await p.locator('.book-tile').count(),2);await h.visible('#book-search');await h.visible('#book-filter');await h.visible('#save');await h.visible('#publish');});
add('admin-shelf','A02','도서 제목 검색','도서가 여러 권 존재한다','앨리스를 검색한다','앨리스만 표시된다',async(p,h)=>{await h.admin();await p.locator('#book-search').fill('앨리스');h.eq(await p.locator('.book-tile:visible').count(),1);await h.contains('.book-tile:visible','앨리스');});
add('admin-shelf','A03','검색 결과 없음과 검색 해제','관리자가 도서 목록에 있다','없는 제목을 검색한 뒤 검색어를 지운다','빈 결과 안내 후 모든 도서가 다시 표시된다',async(p,h)=>{await h.admin();await p.locator('#book-search').fill('QA-NO-SUCH-BOOK');await h.visible('#shelf-empty');h.eq(await p.locator('.book-tile:visible').count(),0);await p.locator('#book-search').fill('');h.eq(await p.locator('.book-tile:visible').count(),2);});
add('admin-shelf','A04','공개 상태별 필터','기존 책 두 권이 공개 대상이다','비공개 초안과 공개 대상을 차례로 고른다','각 조건에 맞는 도서만 표시된다',async(p,h)=>{await h.admin();await p.locator('#book-filter').selectOption('draft');h.eq(await p.locator('.book-tile:visible').count(),0);await p.locator('#book-filter').selectOption('public');h.eq(await p.locator('.book-tile:visible').count(),2);});
add('admin-shelf','A05','모델 보관함 검색','기본 모델 9개가 존재한다','모델 보관함에서 토끼를 검색한다','일치하는 모델만 표시된다',async(p,h)=>{await h.models();await p.locator('#model-search').fill('토끼');h.check(await p.locator('.model-card:visible').count()>=1,'검색 결과');for(const text of await p.locator('.model-card:visible h2').allTextContents())h.check(text.includes('토끼'),'일치하는 모델만');});
add('admin-shelf','A06','설정 파일 내려받기','관리자에 책과 모델 데이터가 있다','공개 및 안내에서 설정 내려받기를 누른다','설정 백업 파일이 내려받아진다',async(p,h)=>{await h.admin();await p.locator('[data-tab="settings"]').click();const wait=p.waitForEvent('download');await p.locator('#export').click();const d=await wait;h.eq(d.suggestedFilename(),'on-the-book-library.json');await d.saveAs(h.evidence+'/A06-library.json');});
add('admin-shelf','A07','사용자 화면 새 창 링크','관리자 도서 보관함에 있다','사용자 화면 열기를 누른다','새 창에서 사용자 화면이 정상 표시된다',async(p,h)=>{await h.admin();const wait=p.waitForEvent('popup');await p.locator('.visit-client').click();const child=await wait;await child.locator('#start-button').waitFor();h.check(child.url().endsWith('/client/'),'사용자 URL');await child.close();});
add('admin-shelf','A08','스튜디오 요청 실패와 재시도','관리자 데이터 응답에 일시 장애가 있다','다시 시도를 누른다','오류 안내 후 도서 보관함으로 복구한다',async(p,h)=>{let fail=true;await p.route('**/api/studio',r=>r.request().method()==='GET'&&fail?r.fulfill({status:500,contentType:'application/json',body:'{"error":"QA 장애"}'}):r.continue());await p.goto(h.base+'/admin/');await h.visible('#retry');fail=false;await p.locator('#retry').click();await h.visible('.book-shelf');});

for(const [i,field,value,why]of [[1,'title','','빈 제목'],[2,'englishTitle','','빈 영문 제목'],[3,'year','0','출간 연도 하한 미만'],[4,'year','2027','출간 연도 상한 초과'],[5,'year','1.5','정수가 아닌 연도'],[6,'source','not-a-url','잘못된 출처 주소'],[7,'source','javascript:alert(1)','실행 가능한 출처 주소']])add('book-validation','V0'+i,`도서 입력 검증: ${why}`,'새 책 정보 입력창이 열려 있다',`${why}을 입력하고 책 만들기를 누른다`,'입력창을 유지하고 잘못된 입력을 차단한다',async(p,h)=>{await h.admin();await p.locator('#new-book').click();const f=p.locator('#book-form');await f.locator(`[name="${h.data.field}"]`).fill(h.data.value);await f.locator('button[type="submit"]').click();await h.visible('#book-form');h.check(!(await f.locator(`[name="${h.data.field}"]`).evaluate(e=>e.checkValidity())),'브라우저 입력 검증');},{field,value});
add('book-validation','V08','공백으로만 된 제목 차단','새 책 정보 입력창이 열려 있다','제목에 공백만 입력하고 책을 만든다','책 생성 전에 의미 있는 제목을 요청한다',async(p,h)=>{await h.admin();await p.locator('#new-book').click();await p.locator('#book-form [name="title"]').fill('   ');await p.locator('#book-form button[type="submit"]').click();if(await p.locator('#book-form').isVisible())return;const wait=p.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/api/studio'));await p.locator('#save').click();const response=await wait;const body=await response.json();await h.waitText('#save-state','저장하지 못했어요');h.check(false,'공백 제목 생성 허용 후 저장 '+response.status()+': '+body.error);});
add('book-validation','V09','문자열을 HTML로 실행하지 않음','새 책 제목에 특수문자가 포함된다','태그와 한글 및 이모지가 있는 제목으로 책을 만든다','문자열을 그대로 표시하고 스크립트를 실행하지 않는다',async(p,h)=>{await h.admin();await p.locator('#new-book').click();const title='<img src=x onerror="window.__qaXss=1"> 한글 📚';await p.locator('#book-form [name="title"]').fill(title);await p.locator('#book-form button[type="submit"]').click();await h.visible('.world-topbar');h.eq(await p.locator('.world-topbar > strong').innerText(),title);h.eq(await p.evaluate(()=>window.__qaXss||0),0);});
add('book-validation','V10','새 비공개 책의 기본 챕터와 저장','관리자가 새 책을 만들 수 있다','정상 제목으로 비공개 책을 만들고 임시 저장한다','기본 챕터 1개와 비공개 상태로 저장되고 사용자 책장에는 없다',async(p,h)=>{await h.createBook('QA 비공개 책');h.eq(await p.locator('[data-chapter-row]').count(),1);await h.save();const d=await h.read();h.check(d.library.books.some(b=>b.title==='QA 비공개 책'&&!b.published),'비공개 저장');const live=await h.read(true);h.check(!live.books.some(b=>b.title==='QA 비공개 책'),'공개 목록에 없음');});

for(const [i,field,value,why]of [[1,'width','39','가로 하한 미만'],[2,'width','121','가로 상한 초과'],[3,'depth','39','세로 하한 미만'],[4,'depth','101','세로 상한 초과'],[5,'floorPageSize','39','페이지 글자 수 하한 미만'],[6,'floorPageSize','401','페이지 글자 수 상한 초과'],[7,'floorZoom','1.9','카메라 여백 상한 초과'],[8,'reactionMultiplier','4.1','접근 배율 상한 초과']])add('chapter-validation','B0'+i,`챕터 입력 검증: ${why}`,'챕터 설정창이 열려 있다',`${why} 값을 입력하고 변경 적용을 누른다`,'잘못된 입력을 차단하고 설정창을 유지한다',async(p,h)=>{await h.open();await h.chapterForm();const f=p.locator('#chapter-form');await f.locator(`[name="${h.data.field}"]`).fill(h.data.value);await f.locator('.primary-button').click();await h.visible('#chapter-form');h.check(!(await f.locator(`[name="${h.data.field}"]`).evaluate(e=>e.checkValidity())),'범위 검증');},{field,value});

add('admin-edit','E01','저장 전 편집 내용 유지','앨리스의 도서 편집 화면이다','책 제목을 바꾸고 나가기에서 계속 편집을 누른다','편집 화면과 바꾼 제목이 유지된다',async(p,h)=>{await h.open();await h.rename('QA 계속 편집');await p.locator('#back-library').click();await h.visible('.leave-editor-dialog');await p.locator('[data-leave="cancel"]').click();await h.contains('.world-topbar > strong','QA 계속 편집');});
add('admin-edit','E02','저장하지 않고 나가기','책 제목을 변경했지만 저장하지 않았다','저장하지 않고 나가기를 선택한 뒤 책을 다시 연다','기존 제목으로 되돌아온다',async(p,h)=>{await h.open();await h.rename('QA 버릴 변경');await p.locator('#back-library').click();await p.locator('[data-leave="discard"]').click();await p.locator('[data-open-book="alice"]').click();await h.contains('.world-topbar > strong','이상한 나라의 앨리스');});
add('admin-edit','E03','저장 후 나가기','책 제목을 변경했지만 저장하지 않았다','저장 후 나가기를 선택하고 새로고침한다','도서 목록에 변경한 제목이 남는다',async(p,h)=>{await h.open();await h.rename('QA 저장 후 나가기');await p.locator('#back-library').click();await p.locator('[data-leave="save"]').click();await h.visible('.book-shelf');await p.reload();await h.contains('[data-open-book="alice"]','QA 저장 후 나가기');});
add('admin-edit','E04','실행 취소와 다시 실행','도서 제목 변경을 적용했다','실행 취소 후 다시 실행한다','원래 제목과 변경한 제목이 순서대로 복원된다',async(p,h)=>{await h.open();await h.rename('QA 실행 취소');await p.locator('#undo').click();await h.contains('.world-topbar > strong','이상한 나라의 앨리스');await p.locator('#redo').click();await h.contains('.world-topbar > strong','QA 실행 취소');});
add('admin-edit','E05','챕터 이동 중 같은 3D 화면 유지','앨리스 편집 화면이 열려 있다','여러 챕터를 순서대로 선택한다','선택한 챕터가 활성화되고 3D 화면이 재생성되지 않는다',async(p,h)=>{await h.open();await p.locator('#studio-world canvas').evaluate(e=>e.dataset.qaIdentity='original');await p.locator('[data-chapter]').nth(1).click();await p.waitForFunction(()=>document.querySelector('.world-workspace').dataset.travelling==='false');await h.contains('#placement-target','작아지는 문');h.eq(await p.locator('#studio-world canvas').getAttribute('data-qa-identity'),'original');});
add('admin-edit','E06','챕터 이름과 본문 저장','기존 첫 챕터를 편집한다','제목과 한글 및 이모지 본문을 바꾼 뒤 저장하고 다시 연다','입력한 챕터 제목과 본문이 유지된다',async(p,h)=>{await h.open();await h.chapterForm();await p.locator('#chapter-form [name="title"]').fill('QA 챕터 📚');await p.locator('#chapter-form [name="body"]').fill('첫 문단입니다. 📚\n\n둘째 문단입니다.');await p.locator('#chapter-form .primary-button').click();await h.save();await p.reload();await p.locator('[data-open-book="alice"]').click();await h.chapterForm();h.eq(await p.locator('#chapter-form [name="body"]').inputValue(),'첫 문단입니다. 📚\n\n둘째 문단입니다.');});
add('admin-edit','E07','챕터 순서 키보드 변경과 취소','앨리스의 첫 챕터가 선택되어 있다','순서 손잡이에서 Alt+아래를 누르고 실행 취소한다','챕터 순서가 바뀌고 취소하면 원래 순서가 된다',async(p,h)=>{await h.open();const ids=await p.locator('[data-chapter-row]').evaluateAll(es=>es.map(e=>e.dataset.chapterRow));await p.locator('[data-chapter-drag]').first().focus();await p.keyboard.press('Alt+ArrowDown');h.eq(await p.locator('[data-chapter-row]').nth(1).getAttribute('data-chapter-row'),ids[0]);await p.locator('#undo').click();h.eq(await p.locator('[data-chapter-row]').first().getAttribute('data-chapter-row'),ids[0]);});
add('admin-edit','E08','챕터 추가를 취소하면 원상 복귀','기존 챕터 개수를 확인했다','챕터 추가를 누른 뒤 입력창을 닫는다','추가 확정 전 취소한 챕터는 남지 않는다',async(p,h)=>{await h.open();const n=await p.locator('[data-chapter-row]').count();await p.locator('#add-chapter').click();await h.visible('#chapter-form');await p.locator('dialog .close-modal').click();h.eq(await p.locator('[data-chapter-row]').count(),n,'추가 취소 시 챕터 개수');});
add('admin-edit','E09','마지막 챕터 삭제 방지','기본 챕터가 하나뿐인 새 책','챕터 설정을 연다','유일한 챕터의 삭제 버튼이 비활성이다',async(p,h)=>{await h.createBook('QA 한 챕터');await h.chapterForm();h.check(await p.locator('#delete-chapter').isDisabled(),'마지막 챕터 삭제 제한');});
add('admin-edit','E10','도서 삭제 확인에서 취소','기존 도서의 삭제를 요청한다','삭제 확인창에서 취소한다','도서와 챕터가 유지된다',async(p,h)=>{await h.open();await p.locator('#edit-book').click();await p.locator('#delete-book').click();await h.visible('#cancel-action');await p.locator('#cancel-action').click();await h.contains('.world-topbar > strong','이상한 나라의 앨리스');h.eq(await p.locator('[data-chapter-row]').count(),6);});

add('admin-models','M01','모델 선택과 위치 속성','모델이 있는 첫 챕터의 편집 화면','모델 목록의 첫 모델을 선택한다','모델 이름과 실제 위치 및 애니메이션 설정을 확인할 수 있다',async(p,h)=>{await h.open();await p.locator('[data-select-model]').first().click();await h.visible('#object-form');for(const key of ['x','y','z','scale','rotation','radius'])await h.visible('#object-form [name="'+key+'"]');});
add('admin-models','M02','모델 높이 변경 저장','첫 챕터 모델을 선택했다','높이를 2로 바꾸고 임시 저장한다','저장된 모델의 높이가 2이다',async(p,h)=>{await h.open();const first=p.locator('[data-select-model]').first();const id=await first.getAttribute('data-select-model');await first.click();await p.locator('#object-form [name="y"]').fill('2');await p.locator('#object-form [name="y"]').press('Tab');await h.save();const d=await h.read();h.eq(d.library.books[0].chapters[0].placements.find(x=>x.id===id).y,2);});
add('admin-models','M03','메인 모델 변경','첫 챕터에 여러 모델이 있다','보조 모델을 선택해 메인 모델로 지정하고 저장한다','새 메인 모델이 목록과 저장 데이터에 반영된다',async(p,h)=>{await h.open();const item=p.locator('[data-select-model]').nth(1);const id=await item.getAttribute('data-select-model');await item.click();await p.locator('#make-main').click();await h.save();const d=await h.read();h.eq(d.library.books[0].chapters[0].mainPlacementId,id);await h.contains('[data-select-model="'+id+'"]','메인');});
add('admin-models','M04','메인 모델 삭제 시 대체 모델 필수','메인 모델과 보조 모델들이 있다','메인 모델 삭제를 누르고 대체 모델 없이 확정한다','대체 모델 선택창을 유지한다',async(p,h)=>{await h.open();await p.locator('[data-select-model]').first().click();await p.locator('#delete-object').click();await h.visible('select[name="replacement"]');await p.locator('dialog button[type="submit"]').click();h.check(!(await p.locator('[name="replacement"]').evaluate(e=>e.checkValidity())),'대체 모델 필수');h.eq(await p.locator('[data-select-model]').count(),3);});
add('admin-models','M05','모델 복제','첫 챕터의 모델이 선택되어 있다','복제를 누른다','겹치지 않는 위치에 고유 식별자를 가진 모델이 하나 추가된다',async(p,h)=>{await h.open();await p.locator('[data-select-model]').first().click();await p.locator('#duplicate-object').click();h.eq(await p.locator('[data-select-model]').count(),4);const ids=await p.locator('[data-select-model]').evaluateAll(es=>es.map(e=>e.dataset.selectModel));h.eq(new Set(ids).size,4);await h.save();});
add('admin-models','M06','첫 모델을 드래그해 배치','모델이 없는 새 책의 챕터','기본 토끼 모델을 월드로 끌어 놓는다','모델이 추가되며 자동으로 메인 모델이 된다',async(p,h)=>{await h.createBook('QA 모델 배치');await h.dragModel();h.eq(await p.locator('[data-select-model]').count(),1);await h.contains('[data-select-model]','메인');await h.save();});
add('admin-models','M07','편집 도구 단축키와 Escape','모델을 선택한 편집 화면','E, S, R, Escape를 차례로 누른다','방향, 크기, 범위, 이동 도구가 각각 활성화된다',async(p,h)=>{await h.open();await p.locator('[data-select-model]').first().click();for(const[key,id]of[['e','tool-rotate'],['s','tool-scale'],['r','tool-radius'],['Escape','tool-move']]){await p.keyboard.press(key);h.check((await p.locator('#'+id).getAttribute('class')||'').includes('active'),'도구 '+key);}});
add('admin-models','M08','관리자 독자 체험과 편집 복귀','편집 중인 챕터가 있다','독자 체험에서 다른 챕터를 보고 편집으로 돌아온다','본문과 장면을 체험하고 원래 편집 화면으로 돌아온다',async(p,h)=>{await h.open();await p.locator('#preview-client').click();await h.visible('#exit-reader');await h.visible('.reader-world canvas');await p.getByLabel('체험할 챕터').selectOption('1');await h.waitText('#floor-title','작아지는 문');await p.locator('#exit-reader').click();await h.visible('.world-tools');h.eq(await p.locator('#exit-reader').count(),0);});

for(const[id,file,match,title]of [['U01','invalid.glb','올바른 GLB','손상된 GLB 거부'],['U02','unrigged.glb','뼈대','뼈대 없는 GLB 거부'],['U03','oversize.glb','25MB','25MB 초과 GLB 거부']])add('uploads',id,title,'새 모델 등록창이 열려 있다',`${file} 파일을 선택한다`,'등록 실패 이유를 알리고 저장 버튼을 다시 사용할 수 있다',async(p,h)=>{await h.models();await p.locator('#new-model').click();await p.locator('#model-form [name="file"]').setInputFiles(h.fixtures+'/'+h.data.file);await h.waitText('#upload-status',h.data.match);h.check(!(await p.locator('#model-submit').isDisabled()),'업로드 실패 후 재시도 가능');},{file,match});
add('uploads','U04','정상 애니메이션 모델 등록과 저장','유효한 애니메이션 GLB 파일이 준비되어 있다','이름과 사용 권한 및 파일을 입력하고 보관함에 등록한 뒤 저장한다','모델과 애니메이션 정보가 보관함에 저장된다',async(p,h)=>{await h.models();await p.locator('#new-model').click();await p.locator('[name="name"]').fill('QA 움직이는 모델');await p.locator('[name="credit"]').fill('QA 자체 생성');await p.locator('[name="file"]').setInputFiles(h.fixtures+'/animated.glb');await h.waitText('#upload-status','업로드 완료');await p.locator('#model-submit').click();await h.save();const d=await h.read();const m=d.library.models.find(x=>x.name==='QA 움직이는 모델');h.check(m?.rigged&&m.clips.includes('Float'),'뼈대 및 애니메이션');});
add('uploads','U05','파일 없이 모델 등록 차단','이름과 사용 권한만 입력된 새 모델','파일을 선택하지 않고 보관함 등록을 누른다','유효한 파일을 먼저 등록하도록 안내한다',async(p,h)=>{await h.models();await p.locator('#new-model').click();await p.locator('[name="name"]').fill('QA 파일 없음');await p.locator('[name="credit"]').fill('QA');await p.locator('#model-submit').click();await h.waitText('#toast','GLB 파일');await h.visible('#model-form');});
add('uploads','U06','사용 중인 모델 삭제 차단','토끼 모델이 여러 챕터에 배치되어 있다','모델 정보에서 삭제를 누른다','장면에서 먼저 제거하도록 안내하고 모델을 유지한다',async(p,h)=>{await h.models();await p.locator('[data-edit-model="rabbit"]').click();await p.locator('#delete-model').click();await h.waitText('#toast','먼저 모델을 제거');await h.visible('#model-form');});
for(const[id,file,match]of[['U07','invalid.png','올바른 PNG'],['U08','oversize.png','5MB']])add('uploads',id,'잘못된 표지 이미지 거부: '+file,'도서 정보창이 열려 있다',`${file}을 표지로 선택한다`,'파일 오류를 안내하고 변경 적용 버튼을 다시 사용할 수 있다',async(p,h)=>{await h.open();await p.locator('#edit-book').click();await p.locator('#book-cover-file').setInputFiles(h.fixtures+'/'+h.data.file);await h.waitText('#toast',h.data.match);h.check(!(await p.locator('#book-form button[type="submit"]').isDisabled()),'업로드 후 편집 가능');},{file,match});
add('uploads','U09','표지 이미지 등록과 사용자 반영','유효한 PNG 파일과 공개 도서가 있다','표지를 올려 적용하고 공개한다','사용자 책장에 등록한 표지가 로드된다',async(p,h)=>{await h.open();await p.locator('#edit-book').click();await p.locator('#book-cover-file').setInputFiles(h.fixtures+'/valid.png');await h.waitText('#book-cover-status','업로드 완료');await p.locator('#book-form button[type="submit"]').click();await h.save(true);await h.home();await p.locator('#library-button').click();const img=p.locator('[data-book="alice"] img');await img.waitFor();await img.evaluate(e=>e.decode());h.check(await img.evaluate(e=>e.naturalWidth>0),'표지 디코딩');});
add('uploads','U10','바닥 이미지 등록과 저장','도서 편집 화면이 열려 있다','PNG 바닥 이미지를 등록하고 저장한 뒤 다시 연다','등록 이미지가 바닥 이미지 목록에 남는다',async(p,h)=>{await h.open();const n=await p.locator('[data-floor-asset]').count();await p.locator('#upload-floor-asset').setInputFiles(h.fixtures+'/valid.png');await h.waitText('#toast','바닥 이미지를 등록');h.eq(await p.locator('[data-floor-asset]').count(),n+1);await h.save();await h.open();h.eq(await p.locator('[data-floor-asset]').count(),n+1);});

add('integration','I01','임시 저장과 공개 분리','공개된 앨리스 도서가 있다','관리자에서 제목을 바꾸고 임시 저장만 한다','관리자는 변경 제목을 보며 사용자 화면은 기존 제목을 표시한다',async(p,h)=>{await h.open();await h.rename('QA 공개 전 제목');await h.save();await h.home();await h.contains('.hero-copy h2','이상한 나라의 앨리스');await h.admin();await h.contains('[data-open-book="alice"]','QA 공개 전 제목');});
add('integration','I02','관리자 편집에서 공개와 사용자 확인까지','관리자가 공개 도서를 편집한다','제목을 변경해 공개하고 사용자 화면을 새로 연다','변경한 책 제목이 사용자 첫 화면과 책장에 표시된다',async(p,h)=>{await h.open();await h.rename('QA 새로 공개한 이야기');await h.save(true);await h.home();await h.contains('.hero-copy h2','QA 새로 공개한 이야기');await p.locator('#library-button').click();await h.contains('[data-book="alice"]','QA 새로 공개한 이야기');});
add('integration','I03','비공개 전환 후 책장 제외','공개 중인 앨리스가 있다','공개 대상 체크를 해제하고 공개한다','사용자 책장에서 앨리스가 사라지고 오즈는 남는다',async(p,h)=>{await h.open();await p.locator('#edit-book').click();await p.locator('[name="published"]').uncheck();await p.locator('#book-form button[type="submit"]').click();await h.save(true);await h.home();await p.locator('#library-button').click();h.eq(await p.locator('[data-book="alice"]').count(),0);h.eq(await p.locator('[data-book="oz"]').count(),1);});
add('integration','I04','저자 및 권리 정보 없는 공개 차단','공개 대상 도서의 저자와 권리 정보가 비어 있다','공개를 누른다','누락 정보 안내가 나오며 공개 데이터는 그대로 유지된다',async(p,h)=>{await h.open();await p.locator('#edit-book').click();await p.locator('[name="author"]').fill('');await p.locator('[name="rights"]').fill('');await p.locator('#book-form button[type="submit"]').click();await p.locator('#publish').click();await h.waitText('#toast','권리 정보를 완성');const live=await h.read(true);h.eq(live.books[0].author,'루이스 캐럴');});
add('integration','I05','메인 모델 없는 챕터 공개 차단','새 공개 대상 책에 모델이 없다','임시 저장 후 공개를 누른다','초안 저장은 되고 공개는 메인 모델 안내와 함께 거부된다',async(p,h)=>{await h.createBook('QA 메인 없음',true);await h.save();const r=p.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/api/studio'));await p.locator('#publish').click();h.eq((await r).status(),400);await h.waitText('#toast','메인 모델');const live=await h.read(true);h.check(!live.books.some(b=>b.title==='QA 메인 없음'),'공개 안 됨');});
add('integration','I06','저장 오류 후 수정 내용 유지와 재시도','책 제목을 수정한 상태에서 저장 요청이 실패한다','실패 안내를 확인한 뒤 다시 저장한다','편집 내용이 보존되고 두 번째 저장이 성공한다',async(p,h)=>{await h.open();await h.rename('QA 저장 재시도');let fail=true;await p.route('**/api/studio',r=>r.request().method()==='PUT'&&fail?r.fulfill({status:500,contentType:'application/json',body:'{"error":"QA 저장 실패"}'}):r.continue());await p.locator('#save').click();await h.waitText('#save-state','저장하지 못했어요');await h.contains('.world-topbar > strong','QA 저장 재시도');fail=false;await h.save();});
add('integration','I07','다른 창의 저장과 충돌 처리','두 관리자 창이 같은 도서를 열었다','첫 창에서 저장한 뒤 오래된 둘째 창이 저장한다','둘째 창은 덮어쓰지 않고 충돌을 알린다',async(p,h)=>{await h.open();const other=await p.context().newPage();await other.goto(h.base+'/admin/');await other.locator('[data-open-book="alice"]').click();await other.locator('#edit-book').click();await other.locator('[name="title"]').fill('QA 두 번째 창');await other.locator('#book-form button[type="submit"]').click();await h.rename('QA 첫 번째 창');await h.save();const r=other.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/api/studio'));await other.locator('#save').click();h.eq((await r).status(),409);await other.locator('#toast').waitFor();h.check((await other.locator('#toast').innerText()).includes('다른 창'),'충돌 설명');const d=await h.read();h.eq(d.library.books[0].title,'QA 첫 번째 창');await other.close();});
add('integration','I08','저장 중 버튼 중복 요청 방지','변경 내용을 저장하는 응답이 대기 중이다','저장 중 저장 및 공개 버튼을 확인한다','두 버튼을 비활성화하고 완료 후 활성화한다',async(p,h)=>{await h.open();await h.rename('QA 저장 중');let release;const gate=new Promise(r=>release=r);await p.route('**/api/studio',async r=>{if(r.request().method()==='PUT')await gate;await r.continue();});await p.locator('#save').click();h.check(await p.locator('#save').isDisabled(),'저장 비활성');h.check(await p.locator('#publish').isDisabled(),'공개 비활성');release();await h.waitText('#save-state','변경사항 저장됨');h.check(!(await p.locator('#save').isDisabled()),'저장 재활성');});

add('auth-basic','S01','비로그인 관리자 접근 보호','비밀번호 보호가 켜진 별도 환경','관리자 화면에 접속한다','로그인 화면이 표시되고 도서 편집 화면은 보이지 않는다',async(p,h)=>{await p.goto(h.auth+'/admin/');await h.visible('#login-form');h.eq(await p.locator('.book-shelf').count(),0);});
add('auth-basic','S02','빈 비밀번호 차단','관리자 로그인 화면','비밀번호 없이 입장을 누른다','필수 입력을 요구하고 로그인 화면을 유지한다',async(p,h)=>{await p.goto(h.auth+'/admin/');await p.locator('#login-form button').click();h.check(!(await p.locator('[name="password"]').evaluate(e=>e.checkValidity())),'비밀번호 필수');});
add('auth-basic','S03','잘못된 비밀번호 안내','관리자 로그인 화면','틀린 비밀번호를 제출한다','비밀번호가 일치하지 않는다는 안내가 표시된다',async(p,h)=>{await p.goto(h.auth+'/admin/');await p.locator('[name="password"]').fill('incorrect-qa');await p.locator('#login-form button').click();await h.waitText('#login-error','일치하지 않습니다');});
add('auth-basic','S04','올바른 로그인과 새로고침 유지','올바른 테스트 비밀번호가 있다','로그인한 뒤 새로고침한다','로그인 상태와 관리자 보관함이 유지된다',async(p,h)=>{await h.login();await p.reload();await h.visible('.book-shelf');await h.contains('.studio-user','관리자 로그인됨');});
add('auth-basic','S05','로그아웃 후 관리자 접근 차단','로그인한 관리자','로그아웃을 누르고 관리자 화면을 다시 연다','로그인 화면으로 돌아간다',async(p,h)=>{await h.login();await p.locator('#logout').click();await h.visible('#login-form');await p.reload();await h.visible('#login-form');});
add('auth-basic','S06','인증 없는 초안 미리보기 차단','로그인하지 않은 사용자','초안 미리보기 주소에 접속한다','초안 내용 대신 관리자 로그인 필요 안내를 표시한다',async(p,h)=>{await p.goto(h.auth+'/client/?preview=draft&book=alice&chapter=alice-1');await h.visible('#retry');await h.contains('body','관리자 로그인이 필요합니다');h.eq(await p.locator('#world canvas').count(),0);});
add('auth-basic','S07','인증 없이 공개 독서 가능','비밀번호 보호가 켜진 환경의 일반 사용자','사용자 첫 화면에 접속한다','로그인 요구 없이 공개 도서를 볼 수 있다',async(p,h)=>{await p.goto(h.auth+'/client/');await h.visible('#start-button');});
add('auth-basic','S08','세션 종료 후 편집 저장 거부','로그인 후 제목을 편집했다','세션을 지우고 저장을 누른다','로그인 필요 안내를 표시하며 편집 내용은 유지한다',async(p,h)=>{await h.login();await p.locator('[data-open-book="alice"]').click();await h.rename('QA 세션 만료');await p.context().clearCookies();const wait=p.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/api/studio'));await p.locator('#save').click();h.eq((await wait).status(),401);await h.waitText('#toast','로그인');await h.contains('.world-topbar > strong','QA 세션 만료');});

for(const[width,height]of[[390,844],[768,1024],[1024,768],[1600,1000]])for(const app of['client','admin'])add('responsive',`P${app==='client'?'C':'A'}${width}`,`${app} 화면 크기 ${width}×${height}`,`${width}×${height} 화면의 사용자`,`${app} 첫 화면과 주요 동작을 확인한다`,'가로 넘침 없이 주요 버튼을 실제로 누를 수 있다',async(p,h)=>{await p.setViewportSize({width:h.data.width,height:h.data.height});if(h.data.app==='client'){await h.home();await p.locator('#start-button').click();await h.visible('#map-button');await h.closeDialogs();if(h.data.width<700)await h.visible('.touch-pad');}else{await h.admin();await p.locator('#new-book').click();await h.visible('#book-form');await p.keyboard.press('Escape');}const m=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:innerWidth}));h.check(m.scroll<=m.client+1,'가로 넘침 '+JSON.stringify(m));},{width,height,app});
add('responsive','P09','작은 화면의 편집 주요 도구 접근','390×844 화면의 관리자','책을 열어 저장 및 공개와 도구 영역을 확인한다','주요 편집 버튼이 화면 안에 있고 서로 겹쳐 가려지지 않는다',async(p,h)=>{await p.setViewportSize({width:390,height:844});await h.open();const result=await p.locator('#save').evaluate(e=>{const r=e.getBoundingClientRect();const x=r.x+r.width/2,y=r.y+r.height/2;return{right:r.right,bottom:r.bottom,visible:x>=0&&x<innerWidth&&y>=0&&y<innerHeight&&e.contains(document.elementFromPoint(x,y))};});h.check(result.visible,'모바일 저장 버튼 접근 불가 '+JSON.stringify(result));});
add('responsive','P10','동작 줄이기 설정에서 화면 이동','운영체제의 동작 줄이기를 선택했다','사용자 화면에서 다음 챕터로 이동한다','화면이 멈추지 않고 다음 챕터를 표시한다',async(p,h)=>{await p.emulateMedia({reducedMotion:'reduce'});await h.explore();await p.locator('#next-chapter').click();await h.waitText('#map-button','작아지는 문');await h.visible('#world canvas');});

add('accessibility','X01','사용자 버튼의 이름 제공','사용자 탐험 화면이 열려 있다','보조 기술이 버튼을 읽을 수 있는지 확인한다','보이는 모든 버튼에 읽을 수 있는 이름이 있다',async(p,h)=>{await h.explore();const unnamed=await p.locator('button:visible').evaluateAll(es=>es.filter(e=>!(e.getAttribute('aria-label')||e.textContent).trim()).map(e=>e.id));h.eq(unnamed,[],'이름 없는 버튼');});
add('accessibility','X02','도서 정보창 키보드 초점 제한','도서 정보창이 열려 있다','Tab 키로 여러 번 이동한다','입력창 뒤의 편집 요소로 초점이 이동하지 않는다',async(p,h)=>{await h.open();await p.locator('#edit-book').click();for(let i=0;i<18;i++){await p.keyboard.press('Tab');const focus=await p.evaluate(()=>({tag:document.activeElement?.tagName,id:document.activeElement?.id,dialog:!!document.activeElement?.closest('dialog')}));h.check(focus.dialog||focus.tag==='BODY','초점이 배경 편집 요소로 이동: '+JSON.stringify(focus));}});
add('accessibility','X03','키보드로 첫 화면의 탐험 시작','마우스를 사용하지 않는 사용자','시작 버튼에 초점을 두고 Enter를 누른다','탐험 화면과 사용 안내가 열린다',async(p,h)=>{await h.home();await p.locator('#start-button').focus();await p.keyboard.press('Enter');await h.visible('#map-button');await h.visible('dialog');});
add('accessibility','X04','모델 검색의 빈 결과 안내','관리자 모델 보관함','존재하지 않는 모델 이름을 검색한다','검색 결과가 없음을 읽을 수 있는 문장으로 알린다',async(p,h)=>{await h.models();await p.locator('#model-search').fill('QA-NO-SUCH-MODEL');h.eq(await p.locator('.model-card:visible').count(),0);const text=await p.locator('.studio-content').innerText();h.check(/없|찾을 수|일치/.test(text),'빈 결과 안내 문장 없음');});

add('uat-extended','J01','새 책과 새 GLB 모델의 공개 독서 전체 과정','관리자가 새 공개 도서를 준비한다','새 책을 만들고 GLB를 등록 및 배치한 뒤 본문을 작성해 공개한다','사용자 책장에서 새 책을 골라 모델과 본문을 볼 수 있다',async(p,h)=>{await h.createBook('QA 처음부터 끝까지',true);await p.locator('#new-model').click();await p.locator('#model-form [name="name"]').fill('QA 새 주인공');await p.locator('#model-form [name="credit"]').fill('QA 자체 제작');await p.locator('#model-form [name="file"]').setInputFiles(h.fixtures+'/animated.glb');await h.waitText('#upload-status','업로드 완료');await p.locator('#model-submit').click();const id=await p.locator('[data-model][data-name="qa 새 주인공"]').getAttribute('data-model');await h.dragModel(id);await h.chapterForm();await p.locator('#chapter-form [name="body"]').fill('새로운 책에서 직접 등록한 주인공과 함께 걷습니다.');await p.locator('#chapter-form .primary-button').click();await h.save(true);await h.home();await p.locator('#library-button').click();await p.locator('[data-book]').filter({hasText:'QA 처음부터 끝까지'}).click();await p.locator('#start-button').click();await h.visible('dialog');await h.closeDialogs();await h.waitText('#floor-accessible','직접 등록한 주인공');await h.visible('#world canvas');const broken=await p.locator('#toast').count()?await p.locator('#toast').innerText():'';h.check(!/불러오지|실패/.test(broken),'모델 표시 오류');});
add('uat-extended','J02','저장 도중 추가 수정의 미저장 상태 표시','책 제목의 첫 변경을 저장 중이다','응답이 오기 전에 제목을 다시 변경한다','첫 변경만 저장되고 두 번째 변경은 미저장으로 표시한다',async(p,h)=>{await h.open();await h.rename('QA 첫 저장');let release;const gate=new Promise(r=>release=r);await p.route('**/api/studio',async r=>{if(r.request().method()==='PUT')await gate;await r.continue();});const response=p.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/api/studio'));await p.locator('#save').click();await h.rename('QA 저장 중 추가 편집');release();await response;await h.waitText('#toast','임시 저장');const saved=await h.read();h.eq(saved.library.books[0].title,'QA 첫 저장');await h.contains('.world-topbar > strong','QA 저장 중 추가 편집');await h.contains('#save-state','저장하지 않은');});
add('uat-extended','J03','나가기 중 저장 실패와 재시도','저장되지 않은 도서 제목 변경이 있다','저장 후 나가기의 첫 요청을 실패시키고 다시 시도한다','나가기 창과 변경 내용을 보존하고 재시도 성공 후 나간다',async(p,h)=>{await h.open();await h.rename('QA 나가기 재시도');let fail=true;await p.route('**/api/studio',r=>r.request().method()==='PUT'&&fail?r.abort():r.continue());await p.locator('#back-library').click();await p.locator('[data-leave="save"]').click();await h.waitText('.leave-error','저장하지 못했습니다');await h.visible('.leave-editor-dialog');fail=false;await p.locator('[data-leave="save"]').click();await h.visible('.book-shelf');await h.contains('[data-open-book="alice"]','QA 나가기 재시도');});
add('uat-extended','J04','모든 도서를 비공개로 전환','공개 도서 2권이 있다','각 책의 공개 대상을 해제하고 공개한다','사용자 화면에 준비 중 안내를 표시한다',async(p,h)=>{for(const book of ['alice','oz']){await h.open(book);await p.locator('#edit-book').click();await p.locator('[name="published"]').uncheck();await p.locator('#book-form button[type="submit"]').click();await h.save(book==='oz');}await p.goto(h.base+'/client/');await h.waitText('h1','새로운 이야기를 준비하고 있어요.');});
add('uat-extended','J05','바닥 그림 드래그와 크기 저장','도서 편집 화면에 기본 바닥 이미지가 있다','화살표 그림을 장면에 놓고 크기를 바꾼 뒤 저장한다','바닥 그림의 위치와 크기가 저장된다',async(p,h)=>{await h.open();await p.locator('[data-floor-asset="arrow"]').dragTo(p.locator('#studio-world canvas'),{targetPosition:{x:800,y:720}});await h.visible('#delete-floor-object');await p.locator('#object-form [name="width"]').fill('6');await p.locator('#object-form [name="width"]').press('Tab');await h.save();const d=await h.read();h.check(d.library.books[0].chapters[0].floorDecals.some(x=>x.asset==='arrow'&&x.width===6),'바닥 그림 크기 저장');});
add('uat-extended','J06','등록한 미사용 모델 삭제','새 GLB 모델을 보관함에 등록했다','아직 배치하지 않은 모델을 삭제하고 저장한다','보관함에서 모델이 사라진다',async(p,h)=>{await h.models();await p.locator('#new-model').click();await p.locator('[name="name"]').fill('QA 삭제할 모델');await p.locator('[name="credit"]').fill('QA');await p.locator('[name="file"]').setInputFiles(h.fixtures+'/animated.glb');await h.waitText('#upload-status','업로드 완료');await p.locator('#model-submit').click();const card=p.locator('.model-card').filter({hasText:'QA 삭제할 모델'});await card.locator('[data-edit-model]').click();await p.locator('#delete-model').click();await p.locator('#confirm-action').click();await h.save();h.eq(await p.locator('.model-card').filter({hasText:'QA 삭제할 모델'}).count(),0);});
add('uat-extended','J07','메인 모델 대체 삭제 저장','메인과 보조 모델이 있는 챕터','메인 삭제 시 보조 모델을 대체로 선택한다','기존 메인은 제거되고 선택한 보조 모델이 메인이 된다',async(p,h)=>{await h.open();const ids=await p.locator('[data-select-model]').evaluateAll(es=>es.map(e=>e.dataset.selectModel));await p.locator('[data-select-model]').first().click();await p.locator('#delete-object').click();await p.locator('[name="replacement"]').selectOption(ids[1]);await p.locator('dialog button[type="submit"]').click();await h.save();const d=await h.read();const c=d.library.books[0].chapters[0];h.eq(c.mainPlacementId,ids[1]);h.check(!c.placements.some(x=>x.id===ids[0]),'이전 메인 삭제');});
add('uat-extended','J08','본문 표시 해제와 사용자 반영','첫 챕터에서 모델 접근 시 본문을 표시한다','본문과 카메라 연출 옵션을 해제한 뒤 공개한다','해당 챕터에서 본문 창 없이 탐험할 수 있다',async(p,h)=>{await h.open();await h.chapterForm();await p.locator('[name="floorEnabled"]').uncheck();await p.locator('#chapter-form .primary-button').click();await h.save(true);await h.explore();await p.locator('#app').waitFor({state:'visible'});await p.waitForFunction(()=>!document.querySelector('#app').hasAttribute('aria-busy'));h.check(await p.locator('.floor-reading-controls').isHidden(),'본문 비표시');});

add('edge-cases','Z01','겹치는 모델 반응 범위 저장 방지','모델이 여러 개 있는 챕터','첫 모델의 반응 범위를 최대치로 늘린다','겹침을 안내하고 기존 범위를 유지한다',async(p,h)=>{await h.open();await p.locator('[data-select-model]').first().click();const input=p.locator('#object-form [name="radius"]'),old=await input.inputValue();await input.fill('40');await input.press('Tab');await h.waitText('#toast','겹칩니다');h.eq(await input.inputValue(),old);});
add('edge-cases','Z02','공간 축소 시 외부 모델 검사','모델을 현재 챕터 안쪽의 X=26 위치로 옮겼다','가로와 세로 크기를 최소값으로 줄인다','외부로 벗어나는 배치를 알리고 변경 적용을 막는다',async(p,h)=>{await h.open();await p.locator('[data-select-model]').first().click();await p.locator('#object-form [name="x"]').fill('26');await p.locator('#object-form [name="x"]').press('Tab');h.eq(await p.locator('#object-form [name="x"]').inputValue(),'26');await h.chapterForm();await p.locator('[name="width"]').fill('40');await p.locator('[name="depth"]').fill('40');await p.locator('#chapter-form .primary-button').click();await h.waitText('#toast','새 공간 밖');await h.visible('#chapter-form');});
add('edge-cases','Z03','기본 제공 모델의 정보 수정','기본 토끼 모델의 편집 버튼이 있다','모델 이름을 수정하고 적용한다','모델 종류를 보존하면서 이름이 변경된다',async(p,h)=>{await h.models();await p.locator('[data-edit-model="rabbit"]').click();await p.locator('[name="name"]').fill('QA 이름을 바꾼 토끼');await p.locator('#model-submit').click();h.check(!(await p.locator('#model-form').isVisible()),'기본 모델 편집이 파일 등록 요구로 차단됨');await h.save();const d=await h.read();h.eq(d.library.models.find(x=>x.id==='rabbit').kind,'rabbit');});
add('edge-cases','Z04','모바일 방향 버튼으로 이동','390×844에서 첫 챕터 본문을 보고 있다','뒤로 이동 버튼을 누른 채 유지한다','캐릭터가 이동해 본문 표시 영역에서 벗어난다',async(p,h)=>{await p.setViewportSize({width:390,height:844});await h.explore();await h.visible('.floor-reading-controls');const box=await p.locator('[data-dir="down"]').boundingBox();h.check(box,'방향 버튼');await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();try{await p.locator('.floor-reading-controls').waitFor({state:'hidden',timeout:12000});}finally{await p.mouse.up();}});
add('edge-cases','Z05','탐험 중 새로고침으로 챕터 유지','지도에서 다섯째 챕터로 이동했다','브라우저를 새로고침한다','다섯째 챕터와 본문을 그대로 표시한다',async(p,h)=>{await h.explore();await p.locator('#map-button').click();await p.locator('[data-chapter="4"]').click();await h.waitText('#map-button','장미 정원');await p.reload();await h.waitText('#map-button','장미 정원');await h.visible('.floor-reading-controls');});
add('edge-cases','Z06','영문 검색의 대소문자 무시','영문 제목으로 새 도서를 저장했다','소문자로 도서 제목을 검색한다','대문자가 포함된 같은 도서를 찾는다',async(p,h)=>{await h.createBook('QA English Story');await h.save();await h.admin();await p.locator('#book-search').fill('qa english');h.eq(await p.locator('.book-tile:visible').count(),1);await h.contains('.book-tile:visible','QA English Story');});
add('movement-layout','Z07','모바일 편집 장면의 조작 공간','390×844 화면에서 도서를 편집한다','화면 중앙의 장면을 직접 조작할 수 있는지 확인한다','편집 패널이 중앙의 3D 장면을 전부 가리지 않는다',async(p,h)=>{await p.setViewportSize({width:390,height:844});await h.open();const result=await p.evaluate(()=>{const canvas=document.querySelector('#studio-world canvas');const hits=[];for(const x of [.3,.4,.5,.6,.7])for(const y of [.3,.4,.5,.6,.7]){const e=document.elementFromPoint(innerWidth*x,innerHeight*y);hits.push({x,y,canvas:e===canvas,cover:e?.closest('aside')?.className||e?.className});}return hits;});h.check(result.some(x=>x.canvas),'화면 중앙 25개 지점 모두 편집 패널에 가려짐: '+JSON.stringify(result));});
add('movement-layout','Z08','걸어서 다음 챕터로 자연스럽게 이동','첫 챕터의 메인 모델 앞에서 탐험 중이다','오른쪽 방향키로 챕터 경계를 넘는다','별도 이동 버튼 없이 둘째 챕터로 바뀐다',async(p,h)=>{await h.explore();await p.locator('#world canvas').focus();await p.keyboard.down('ArrowRight');try{await p.waitForURL('**chapter=alice-2',{timeout:20000});}finally{await p.keyboard.up('ArrowRight');}await h.contains('#map-button','작아지는 문');});
add('movement-layout','Z09','같은 모델에 재접근하면 첫 글귀부터 읽기','메인 모델의 글귀를 두 번째 페이지로 넘겼다','모델에서 멀어졌다가 챕터 지도로 다시 접근한다','첫 페이지부터 글귀를 읽는다',async(p,h)=>{await h.explore();await h.visible('.floor-reading-controls');await p.locator('#floor-next').click();await h.contains('#floor-page','2 /');await p.locator('#next-chapter').click();await h.waitText('#map-button','작아지는 문');await p.locator('#prev-chapter').click();await h.waitText('#map-button','흰 토끼');await h.visible('.floor-reading-controls');await h.contains('#floor-page','1 /');});
